### ISSUE TITLE
Заброньовані файли

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#117]
Усім привіт!

Дякую за вашу допомогу та підтримку з перекладом!
Залишилось лише три вільних файли, які я збираюсь перекласти найпізніше до 21 грудня.

Відповідно, треба щось робити з усіма заброньованими файлами.

Будь ласка, усі, у кого є заброньовані файли, підтвердьте протягом тижня (до 19 грудня) своє бажання завершувати над ними роботу.
Далі до 28 грудня, будь ласка, завершіть переклад та/або виправлення зауважень.

Якщо у вас немає можливості завершити переклад, будь ласка, напишіть у відповідному issue про це - тоді я почну переклад зі звільнених файлів.

@unreadableusername, два файли перекладено, проте зауваження не виправлені:
~~B-embedding-git/sections/command-line.asc (PR #163, issue #60)~~
~~B-embedding-git/1-embedding-git.asc (PR #93, issue #59)~~
І їх зовсім небагато...

@tbudurovych, переклад одного файлу розпочато, другого - ще ні:
~~09-git-and-other-scms/sections/import-tfs.asc (issue #42)~~
~~09-git-and-other-scms/sections/client-tfs.asc (PR #86, issue #37)~~

@webknjaz, один файл перекладено, другий схоже не розпочато
~~10-git-internals/1-git-internals.asc (PR #162, issue #43)~~
~~10-git-internals/sections/plumbing-porcelain.asc - зауваження не виправлені (PR #89, issue #48)~~

@VBoden, один файл, переклад у процесі, підтверджено нещодавно:
~~08-customizing-git/sections/config.asc (issue #32)~~

@zmiimz, один файл, нещодавно підтверджено
~~10-git-internals/sections/environment.asc (issue #44)~~

Ще раз дякую!

**Comment by zmiimz** [comment]
Я свій файл закінчу до кінця грудня. Виявилось трохи складніше, ніж це виглядало спочатку.)

**Comment by hedrok** [comment]
Дякую за швидку відповідь )
Якщо є можливість, створюйте PR на ще не завершені переклади. Я їм поставлю позначки "Йде" та "Переклад", і почну коментувати відразу, щоб пришвидшити процес.
У будь-якому разі, до кінця грудня почекаємо )

**Comment by unreadablename** [comment]
Я до 28 завершу переклад

**Comment by hedrok** [comment]
Добре, дякую.
Ну, тобі там зовсім трошки залишилось виправити зауважень ) Щойно ти їх виправиш, я зіллю до master.

**Comment by VBoden** [comment]
Нажаль немає часу завершити переклад((( Створив PR з тим, що я мав. Будуть зауваження до перекладу - виправлю, але більше перекласти не зможу.
(08-customizing-git/sections/config.asc (issue #32))

PS: Ви хлопці молодці, навіть не думав, що так швидко йтиме переклад) Так тримати!

**Comment by hedrok** [comment]
Дякую за те, що є ) Та за швидку реакцію.

**Comment by tbudurovych** [comment]
Я час до часу перекладаю той tfs. Буду переглядати.

**Comment by hedrok** [comment]
Дякую.

**Comment by hedrok** [comment]
@webknjaz, дякую за виправлення зауважень. Файл 10-git-internals/1-git-internals.asc ти теж збираєшся перекладати?

**Comment by webknjaz** [comment]
Так. Вже почав.

**Comment by hedrok** [comment]
Класно. Дуже дякую.

**Comment by hedrok** [comment]
@webknjaz, @tbudurovych, нагадую, що сьогодні та завтра - останні два дні для перекладу. Викладіть все, що встигли перекласти, будь ласка.
@tbudurovych, виправ, будь ласка, зауваження - я тоді зможу залити частину перекладу до master.
@unreadableusername, нагадую, що ти збирався виправити зауваження.

**Comment by unreadablename** [comment]
Саме зараз їду в потязі, завтра все зроблю

**Comment by tbudurovych** [comment]
Я відстав. Якнайшвидше доєднаюся

**Comment by webknjaz** [comment]
@hedrok виклав, жадаю review :)

**Comment by hedrok** [comment]
Review зроблено :sunglasses:

**Comment by hedrok** [comment]
Файл 09-git-and-other-scms/sections/import-tfs.asc (issue #42) переклав: PR #164
