### ISSUE TITLE
Ще про словник

### ISSUE THREAD

**Issue by zmiimz** [progit/progit2-uk#12]
Переглянув трохи термінологію. Здається потрібно ще попрацювати над словником та вирішити, чи насправді звичайної транслітерації достатньо, або ж чи буде хоч якийсь такий-сякий пошук нової термінології. Ви зараз своєю працею фактично творите цю нову термінологію. Тому не бійтеся експериментувати з українською мовою, але уникайте прямої транслітерації. Краще дати англійський термін-відповідник в дужках. Бо ці всі iш'ю, хуки, фетчі, пуші та пули гарно, природно і зрозуміло виглядають тільки для програмістів, які виросли на хронічній відсутності цієї української термінології, але виглядають незграбно і недалекоглядно для всіх інших, особливо якщо врахувати, що цією книгою скористаються в майбутньому можливо десятки тисяч українських школярів та студентів.  Словник можна спробувати узгодити хоча б з українськими перекладами Linux, (напр. http://l10n.kde.org/dictionary/search-translations.php?package=&filename=&teamcode=uk&search=&submitted=Search) та навіть з тією ж MS Windows де вже витрачено купу років на термінологію.  Бо в іншому випадку мова засмічується різним непотребом, який потім всупереч глузду і нормам мови «узаконюють» різні видання та законодавчі акти. Я сподіваюсь, що ви зовсім не бажаєте бути одними з цих узаконювачів і усвідомлюєте свою відповідальність за українську термінологію. Успіху вам і терпіння!

**Comment by tbudurovych** [comment]
дякуємо за теплі та мудрі слова та запрошую долучатися

**Comment by zmiimz** [comment]
Спробую при нагоді.
