### ISSUE TITLE
"тека" повертається?.. :)

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#123]
@tbudurovych, вже дві людини крім мене використовували слово "тека": https://github.com/progit/progit2-uk/pull/89#discussion_r43547316 та https://github.com/progit/progit2-uk/pull/122#discussion-diff-47449980
http://e2u.org.ua/s?w=folder - здається, усі словники перекладають "тека".

Може знімемо заборону на це слово? :)

**Comment by tbudurovych** [comment]
Я не проти

**Comment by hedrok** [comment]
Ура :)
