### ISSUE TITLE
ще питання по словнику

### ISSUE THREAD

**Issue by zmiimz** [progit/progit2-uk#125]
_diff_:: _НЕ УЗГОДЖЕНО_ різниця, відмінності
_diffing_:: _НЕ УЗГОДЖЕНО_ визначення (встановлення) відмінностей

_logging_:: _НЕ УЗГОДЖЕНО_ журналювання

_trace_:: _НЕ УЗГОДЖЕНО_ траса, слід, слід трасування?
_tracing_:: _НЕ УЗГОДЖЕНО_ трасування, відстеження?

які думки щодо цих термінів?

**Comment by zmiimz** [comment]
_override_:: _НЕ УЗГОДЖЕНО_ підміна, переозначення?
_to override_:: _НЕ УЗГОДЖЕНО_ підміняти, переозначувати?

**Comment by hedrok** [comment]
Як я перекладав:
diff: різниця
diffing: порівняння

logging: Зустрічалося лише в значенні "заходити як користувач". Оскільки в усій книзі зустрічається лише два рази, та ще й з різними значеннями, пропоную в твоєму випадку перекласти описово: "контролює, чи будуть записани дані швидкодії до журналу". Якщо додаш до словнику, згадай і друге значення.

trace/tracing: є лише у твоєму файлі :) Гадки не маю, як перекладати... Я ще подумаю... Вікі дає трасування, як ти напевно бачив...

**Comment by hedrok** [comment]
override: Підміна мені особисто не дуже подобається, переозначення - нібито доречно. Тільки обов’язково в дужках напиши, що це про змінні середовища.

**Comment by hedrok** [comment]
@zmiimz, якщо питання розв’язані, закрий цей issue, будь ласка.
