### ISSUE TITLE
Чергова спроба узгодити словник

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#130]
Тут список термінів, для кожного терміну (чи для групи повʼязаних термінів) створено окремий
issue.
У кожному issue наведено приклад використання терміну, поточні варіанти та поточні результати голосування.
Свій голос можна змінювати в будь-який час, аргументувати, сперечатись тощо в коментарях.
Я буду вручну оновлювати результати.
Голосування закінчується 31 січня о 23:59.
Якщо буде декілька варіантів з найбільшою кількістю голосів, застерігаю собі право вибрати або один з них, або зробити допустимими обидва варіанти.
Щоб додати новий варіант, або надати свій голос існуючому варіанту, просто напишіть "+варіант" в коментарі.
Якщо ви вже голосували за якийсь варіант, то в попереднього варіанта ваш голос забирається.
Якщо бажаєте додати варіант без голосування за нього, напишіть "!варіант".
bare #131 чисте (+1) 
blob #132 блоб (+1)
branching #166
bundle, to bundle, packfile, package #133 згорток, згорнути, пака, пакунок (+2)
cherry-pick, to cherry-pick #134: висмикування, висмикнути (+1)
commit, to commit, comitted, commiter #135 коміт/фіксація (!, 2/2)
checkout (noun), to checkout (file), to checkout (branch) #136: отримання, отримати (файл), перейти (на гілку) (+1)
diff, diffing #137: різниця, розрізнення (+3)
executable #161: викона́нний (+3)
fast-forward, fast-forward merge #139 перемота́ння, злиття перемота́нням (+2)
fetch, pull #140 здобути зміни, стягнути зміни (+2)
filter-branch #141: фільтрація гілки (+1)
folder, directory (Git directory, working directory) #138: тека, тека (+4/2)
force (push) #142: примусовий (push) (+1)
fork, to fork, forking #143 відсадок, відсаджувати, відсадження
hosting, hosted, to host #144 гостинг, розташований, розташувати (+2/1)
index, staging area, to stage, to unstage, staged #145 індекс, область споряджання, спорядити, скасувати споряджання, споряджений (+2)
initial (commit) #146: початковий (commit) (+2)
issue (GitHub, issue tracking etc) #147 завдання (+3/1) 
log #148: журнал (+3)
maintainer #149 супровідник (+1/2)
merge, to merge #150 злиття, зливати (+3)
patch, patching #151 латка, латати, латання: (+3)
plumbing, porcelain #152 кухонні, парадні (+2/1)
pull request #153 запит на злиття (+3)
push #154 надсилання змін (+2)
repository #155 сховище (+2)
reset #156 скидання (+3)
revert #157 вивертання, вивернути (+2/1)
squash, squashed #158 зчавлювати, зчавлений (+3)
tag, tagged, to tag, label (GitHub), mark (fast-import) #159 мітка, мічений, мітити, значок, позначка: (+2/1)
to track (file), tracked (file), untracked (file), to track (branch), tracked (branch) #160 стежити (за файлом), відстежуваний (файл), невідстежуваний (файл), стежити (за гілкою) (+3)

Решта словника (якщо потрібно обговорити термін - пишіть тут, створю issue):

annotated tag: анотований tag
back up: резервна копія
branch: гілка
command line: командний рядок
community: спільнота
continuous integration: безперервна інтеграція (http://uk.wikipedia.org/wiki/Безперервна_інтеграція)
dashboard: дошка керування
default: типово
deployment: розгортання (http://uk.wikipedia.org/wiki/Розгортання_програмного_забезпечення)
developer: програміст, розробник
discussion thread: нитка дискусії
dropdown list: випадний список
DVCS: Розподілені системи контролю версій
environment: середовище
Git: Git (не транслітерується)
GUI: графічний інтерфейс
hook: гак
hub: розподілювач
installation: інсталяція
Integration Manager: Керівник Інтеграції
lightweight tag: легкий tag
milestone: віха (http://uk.wikipedia.org/wiki/Віха_(управління_проектами))
modified: змінений
pathspec: специфікація шляхів
policy: політика користування
rebase: перебазування
ref: посилання
reflog: log посилань
refspec: специфікація посилань
remote helper: помічник протоколу
shell: термінал/оболонка в залежності від контексту
snapshot: відбиток
source code: програмний код
Summary (наприкінці розділу): Підсумок
VCS: Системи контролю версій (СКВ)
workflow: процес роботи

Якщо якихось термінів у списку не вистачає - пишіть коментарі.

**Comment by hedrok** [comment]
Запрошую всіх допомогти зі словником: @mzelenyuk @NovikovViktor @softbeehive @tbudurovych @unreadableusername @VBoden @zvisno @webknjaz @zmiimz @greatehop

**Comment by zmiimz** [comment]
executable: викона́нний [файл]. Я знаю, що це слово є в e2u, але там  трохи "швидка настя" в перекладі, бо і виконуваний і виконавчий і командний і виконАнний. Мені здається, що виконавчий чи виконуваний більш відомі. Я б взагалі перекладав просто "програма", по можливості.

**Comment by hedrok** [comment]
Скопіюй, будь ласка, коментар до #161, а тут я його приберу.

**Comment by hedrok** [comment]
@zmiimz, незручно ставити "+" та "!"?.. Я просто гадав, що всім так буде легше: можна писати багато тексту, та поставити окремо біля варіантів "!" та "+", щоб не було двозначностей...

**Comment by tbudurovych** [comment]
shelve, shelving

**Comment by hedrok** [comment]
Я у всій книзі знайшов лише один випадок використання shelve, і жодного shelving:
This uses the ``shelve'' function in TFVC, which we don't cover in detail here. (09-git-and-other-scms/sections/client-tfs.asc)
Може просто залишимо там shelve без перекладу?.. Це функціонал TFVC, чи потрібно нам добирати переклад?.. І воно ще й у лапках...

**Comment by hedrok** [comment]
Шановні @zmiimz, @tbudurovych, @arysin, дуже дякую за допомогу зі словником.
Оновив перший допис - таким буде словник, якщо ви нічого не зміните :)
Залишився тиждень та два дні, і я благаю про допомогу з перекладом commit: #135 Я запропонував декілька варіантів, проте ще не визначився.

Також маю сумніви щодо слів, що я їх позначив знаком оклику:

blob #132 блоб (+1, !)
fetch, pull #140 здобути зміни, втягнути/стягнути зміни (+2)
folder, directory (Git directory, working directory) #138: тека, тека/каталог (2/2, !)
fork, to fork, forking #143 відсадок, відсаджувати, відсадження
hosting, hosted, to host #144 гостинґ, розташований, розташувати (+1, !)
index, staging area, to stage, to unstage, staged #145 індекс, область споряджання, спорядити, скасувати споряджання, споряджений (+2, !)
issue (GitHub, issue tracking etc) #147 питання/заява (!, 1/1) 
plumbing, porcelain #152 кухонні, парадні (+2/1, !)
revert #157 вивертання, вивернути (+2, !)
tag, tagged, to tag, label (GitHub), mark (fast-import) #159 (!, 1/1)

**Comment by hedrok** [comment]
Також суперечливим став checkout (noun), to checkout (file), to checkout (branch) #136: (1/1, !)

**Comment by hedrok** [comment]
Й уваги потребує fast-forward, fast-forward merge #139 перемота́ння, злиття перемота́нням (+2, !)

**Comment by hedrok** [comment]
@tbudurovych, @zmiimz, @arysin, @KhrystynaK, дякую за допомогу!
Сьогодні останній день голосування, якщо нічого не зміниться, мені доведеться самостійно вибирати: #138, #147, #159, #136.
У кожному з цих issue розписав, що я виберу.

**Comment by hedrok** [comment]
Залишив три завдання (issue) відкритими: #143, #135 та #152. Сподіваюсь на допомогу з ними.

**Comment by hedrok** [comment]
Роботу над словником завершено!
Дуже дякую за допомогу, @arysin, @KhrystynaK, @mariana-scorp, @o-pikozh, @tbudurovych, @zmiimz (сподіваюсь нікого не забув).
Запит на злиття зі словником тут: #167

Тарасе, щойно ти зіллєш його до master, почну вичитувати текст і виправляти переклад термінів.
