### ISSUE TITLE
bare

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#131]
голе: 0
ізольоване: 0
незаповнене: 0
очищене: 0
просте: 0
чисте: 1

_Опис_: Сховище (repository), в якому немає робочої директорії, тобто є лише вміст теки .git. Зазвичай використовується на серверах.
_Приклад_: A remote repository is generally a bare repository – a Git repository that has no working directory.

**Comment by hedrok** [comment]
+чисте
!очищене
!голе

**Comment by zmiimz** [comment]
як варіант 
!просте
!незаповнене
!ізольоване
