### ISSUE TITLE
blob

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#132]
_Опис_: Binary Large OBject - великий двійковий обʼєкт (з вікіпедії). У Git так називаються всі обʼєкти, що зберігають просто дані (переважно вміст файлів)
_Приклад_: All the content is stored as tree and blob objects, with trees corresponding to UNIX directory entries and blobs corresponding more or less to inodes or file content.

блоб: 1

**Comment by zmiimz** [comment]
Тут важко, бо є і слово з певним значенням і абревіатура.

**Comment by hedrok** [comment]
Гадаю, доведеться змиритися з "блоб":
+блоб
