### ISSUE TITLE
bundle, to bundle, packfile, package

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#133]
bundle, to bundle:
_Опис_: Файл з даними про коміти Git. За його допомогою можна передати як все сховище (хоча для цього достатньо просто скопіювати теку .git), так і якісь окрему гілку. З цим файлом потім можна працювати як з віддаленим сховищем.
_Приклади_:
(to bundle) If you want to send that repository to someone and you don't have access to a repository to push to, or simply don't want to set one up, you can bundle it with `git bundle create`.
(bundle) Now let's say you do three commits on it and want to send the new commits back via a bundle on a USB stick or email.

packfile:
_Опис_: Файл бази даних Git, що містить низку обʼєктів. Використовується для заощадження місця на диску.
_Приклад_: However, occasionally Git packs up several of these objects into a single binary file called a ``packfile'' in order to save space and be more efficient.

package:
_Опис_: Окрема компонента, яку можна встановлювати, оновлювати та вилучати за допомогою системи керування пакунками.
_Приклад_: You can either install it as a package or via another installer, or download the source code and compile it yourself.

Помістив ці слова в один issue, щоб не перекладати обидва терміни однаково.

згорток, згорнути, пака, пакунок: 2

**Comment by hedrok** [comment]
+згорток, згорнути, пакунок

**Comment by zmiimz** [comment]
мені подобається
+згорток, згорнути, пака, пакунок

**Comment by zmiimz** [comment]
Єдина проблема може бути з пакунком
є в книзі слово package?

**Comment by hedrok** [comment]
Є :'(
Я перекладав package -> пакет, проте бачу, що вікі перекладає "пакунок"
Зараз додам сюди та вигадаю щось інше для packfile...

**Comment by hedrok** [comment]
+згорток, згорнути, файл пакунок, пакунок

**Comment by hedrok** [comment]
@zmiimz, дякую за зауваження.

**Comment by zmiimz** [comment]
може http://sum.in.ua/s/paka ?

**Comment by hedrok** [comment]
Геніально :)
+згорток, згорнути, пака, пакунок

**Comment by hedrok** [comment]
(скажу чесно, я про існування цього слова просто не знав)

**Comment by zmiimz** [comment]
Скажімо так, я майже теж інтуїтивно знайшов. СУМ дуже помагає шукати синоніми, просто потрібно використовувати пошук "в означеннях"

А от де відкриття рідної мови можна робити, то в таких словниках
https://archive.org/details/maloruskonimetsk01zheluoft
https://archive.org/details/maloruskonimetsk02zheluoft
раджу переглянути "для натхнення"

**Comment by hedrok** [comment]
Ех... Я знав, що нам колись можна було писати "и" на початку слова, але не знав, що їх було стільки :)
Дякую за підказки.

Проголосуй, будь ласка, а то я формаліст, і зараз виходить, що твій голос за "+згорток, згорнути, пакунок" :)

**Comment by zmiimz** [comment]
проголосував в попередньому дописі

**Comment by hedrok** [comment]
Дякую.
