### ISSUE TITLE
commit, to commit, comitted, committer

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#135]
_Опис_: Відбиток проекту, збережений у базі даних Git. committer: особа, яка створила коміт, не плутати з автором змін: вони відрізняються, коли зміни надсилаються латкою (patch), і коміт створює хтось інший.
_Приклади_: 
(commit) As you edit files, Git sees them as modified, because you've changed them since your last commit.
(to commit) Every time you commit, or save the state of your project in Git, it basically takes a picture of what all your files look like at that moment and stores a reference to that snapshot.
(commited) If a particular version of a file is in the Git directory, it's considered committed.
(commiter) The author is the person who originally wrote the work, whereas the committer is the person who last applied the work.

коміт (4): KhrystynaK tbudurovych o-pikozh marina-scorp
фіксація (3): arysin zmiimz hedrok

створювати коміт, збережене в коміті (3): KhrystynaK  zmiimz hedrok
комітити, закомічене (2): marina-scorp o-pikozh

творець коміту (3): o-pikozh zmiimz hedrok
комітер (2): arysin marina-scorp

Інші варіанти:
відбитка, відбивати, відбите, відбивальник: 0
відбиток, створити відбиток, збережений/зафіксований відбиток, творець відбитку: 0

**Comment by zmiimz** [comment]
ще додати committer

**Comment by hedrok** [comment]
дякую, додав.

**Comment by hedrok** [comment]
!коміт, створити коміт, збережене в коміті, творець коміту
!фіксація, фіксувати, зафіксоване, фіксувальник
!відбитка, відбивати, відбите, відбивальник

**Comment by hedrok** [comment]
Ще декілька страшних ідей:
!закріпка, закріплювати, закріплені, закріпувальник
!зачіп, причіпляти, причеплені, причеплювальник
Допоможіть! :)

**Comment by khrystyna-skopyk** [comment]
+коміт,створювати коміт, збережене в коміті, творець коміту
Інші варіанти здаються притягнутими за вуха.

**Comment by hedrok** [comment]
Дякую, що знайшли час, Христино!
Можливо й притягнуті за вуха, проте хочеться якогось влучного перекладу, а не просто "коміт"...

**Comment by arysin** [comment]
Найближче англійською це звучить як (commit something to) Transfer something to (a state or place) (з оксфордського тлумачного). Точного перекладу одним словом у нас буде знайти важко.
Якщо підійти творчо: передати, віддати, переказати, ввести, запечатати, зафіксувати.

**Comment by zmiimz** [comment]
може?
!відбиток, створити відбиток, збережений/зафіксований відбиток, творець відбитку

коміт в мене асоціюється з "кодозміна" :)

**Comment by hedrok** [comment]
~~+відбитка, відбивати, відбите, відбивальник:~~
Якщо хтось підтримає цей варіант, його й вибиремо.
Якщо хтось підтримає "фіксація, фіксувати, зафіксоване, фіксувальник", я до нього приєднаюсь.
"відбиток, створити відбиток, збережений/зафіксований відбиток, творець відбитку" мені не подобається тим, що знову необхідно перекладати двоми словами все, крім "commit"
Якщо ніхто більше цих експериментів до завтра не підтримає, я виберу звичайний варіант
"коміт, створити коміт, збережене в коміті, творець коміту"

**Comment by arysin** [comment]
commit тут практично те ж саме, що й в базах даних, то ж я схиляюся до фіксація (зміни) за аналогією з фіксація (транзакції) в СКБД

**Comment by hedrok** [comment]
~~+фіксація, фіксувати, зафіксоване, фіксувальник~~
Ваш голос теж можна зарахувати за "фіксація, фіксувати, зафіксоване, фіксувальник"?

**Comment by tbudurovych** [comment]
+коміт

за фіксацію непроти. ніколи такого просто не чув "в народі"

**Comment by hedrok** [comment]
@arysin, зарахував Ваш голос за "фіксацію" (я так зрозумів Ваш допис)
@zmiimz, @mariana-scorp, @o-pikozh, проголосуйте, будь ласка. Наразі по два голоси у варіантів "фіксація" та "коміт". Не хотів би самостійно визначати, як перекладати це слово.

**Comment by o-pikozh** [comment]
Можливо, якась моя внутрішня обмеженість, але тут я однозначно за "коміт".

**Comment by mariana-scorp** [comment]
Я за "коміт, створити коміт, збережене в коміті, творець коміту". Це, звісно, буде запозичення, але, як на мене, виправдане. Це слово давно увійшло в активний вжиток і красиво творить форми. Я сьогодні в робочому листуванні навіть написала форму "комітитимемо". І вуха не різало :)
Також, замість "створити коміт", ми часто кажемо "закомітити" чи "вкомітити", тож до нього і префікси зручно додавати.

**Comment by hedrok** [comment]
Тепер треба ще й визначатись
!коміт, закомітити, закомічені, комітник
чи
!коміт, створити коміт, збережені в коміті, творець коміту
:)

**Comment by mariana-scorp** [comment]
Я за "коміт, закомітити, закомічені, комітник" =)

**Comment by hedrok** [comment]
Оскільки перемагає "коміт", з цих варіантів я теж обираю
~~+коміт, закомітити, закомічені, комітник~~
Якщо вже використовувати слово, то надавати йому всі права :)

**Comment by hedrok** [comment]
@tbudurovych, оскільки ти написав просто "+коміт", розподілив твій голос по цих двох варіантах.

**Comment by o-pikozh** [comment]
З:
- коміт, закомітити, закомічені, комітник
- коміт, створити коміт, збережені в коміті, творець коміту

-- я обираю проміжний варіант: коміт, закомітити, закомічені, творець коміту (не комітник). Або хоча б комітер.

**Comment by arysin** [comment]
До запозиченого слова варто й запозичений суфікс: комітер

**Comment by mariana-scorp** [comment]
А мені "комітник" подобається. Як вертолітник, співробітник, самітник, лахмітник...

**Comment by arysin** [comment]
Так але всі ці слова незапозичені, ми ж не кажемо гастарбайтник,
спічрайтник, спікник :)

**Comment by mariana-scorp** [comment]
Гаразд. Я можу погодитись на комітера)

**Comment by zmiimz** [comment]
Я за будь-що, крім транслітерації та прямих англіцизмів
+фіксація, фіксувати, зафіксоване, фіксувальник

Якщо візьмете коміт, то велике прохання все-таки зупинитись на варіанті
коміт, створити коміт, збережене в коміті, творець коміту

**Comment by hedrok** [comment]
Після такої емоційної промови я знову перейду в табір "фіксації":
+фіксація, фіксувати, зафіксоване, фіксувальник

Проте це фіксацію не врятує :)
Зробив окремі три голосування: фіксація vs коміт
комітити vs створити коміт (а також закомічене vs збережене в коміті)
та "творець коміту" vs "комітер"

Будь ласка, перевірте, чи правильно я всіх записав (у першому дописі), та долучайтесь ті, кого я не записав :)

Особисто я за "творець коміту", а з "комітити" vs "створити коміт" не визначився.

**Comment by hedrok** [comment]
Добре, хай буде "коміт, створювати коміт, збережене в коміті, творець коміту".
Я довго вагався між "створювати коміт" та "комітити, проте "комітер" мені не подобається, а якщо "творець коміту", то вже логічніше "створювати коміт" з моєї точки зору.
