### ISSUE TITLE
checkout (noun), to checkout (file), to checkout (branch)

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#136]
отримання, отримати (файл), перейти (на гілку): 1
____, відкинути зміни (у файлі), перейти (на гілку)

_Опис_: Операція приведення робочої теки у відповідність з індексом (який може спочатку оновити відповідно до бази даних Git), а також зміни HEAD. Проте користувачу може здаватися, що вона виконує різні операції: отримує файл певної версії, або переключається на гілку.
_Приклади_:
(checkout)
- The working directory is a single checkout of one version of the project.
- If you're familiar with other VCS systems such as Subversion, you'll notice that the command is "clone" and not "checkout"
- You have a bona fide Git repository and a checkout or working copy of the files for that project
- The `--tree-filter` option runs the specified command after each checkout of the project and then recommits the results
- The simplest model of using submodules in a project would be if you were simply consuming a subproject and wanted to get updates from it from time to time but were not actually modifying anything in your checkout.
- This command will by default assume that you want to update the checkout to the `master` branch of the submodule repository.

to checkout (branch)
- When you checkout a branch, it changes _HEAD_ to point to the new branch ref, populates your _Index_ with the snapshot of that commit, then copies the contents of the _Index_ into your _Working Directory_.

to checkout (file)
- you can do the merge and then checkout certain files from one side or the other before committing

Навів купу прикладів, оскільки мені здається, що доволі складно перекласти так, щоб пасувало до всіх випадків використання.

**Comment by hedrok** [comment]
~~+отримання, отримати (файл), переключитись на (гілку)~~

**Comment by khrystyna-skopyk** [comment]
"The command `git checkout -- <file_name>` discards changes in a modified file; that is, all your local changes to the file will disappear, so be careful!"
to checkout (file) - **відкинути зміни (у файлі)**

Також тут "This command will by default assume that you want to update the checkout to the master branch of the submodule repository." - **перейти на гілку master**

**Comment by khrystyna-skopyk** [comment]
**перейти на гілку** (`git checkout <branch_name>`)
Мені переключитися звучить як калька з російської (якщо там так) :)

**Comment by khrystyna-skopyk** [comment]
+____, перейти (на гілку), відкинути зміни (у файлі)

Перше значення checkout бачу вперше, тому не знаю, що запропонувати.

@mariana-scorp @Nastasiya @OksanaKunikevych

**Comment by hedrok** [comment]
+отримання, отримати (файл), перейти (на гілку)

А ось щодо "відкинути зміни" я не згоден. checkout має ще багато можливостей, наприклад,
git checkout HEAD~3 file.txt
Отримує версію HEAD~3 файлу...

**Comment by hedrok** [comment]
Якщо ніхто більше не проголосує, виберу  свій варіант. Враховючи, що в іншому варіанті є ____, гадаю на мене ніхто не образиться :)
