### ISSUE TITLE
diff, diffing

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#137]
різниця, розрізнення: 3

_Опис_: Відображення різниці між файлами/гілками/посиланнями тощо.
_Приклади_:
(diff) There is another way to look at these diffs if you prefer a graphical or external diff viewing program instead.
(diffing) Another interesting problem you can solve this way involves diffing image files.

**Comment by zmiimz** [comment]
Встановлення (виявлення) відмінностей, розрізнення:  "при розрізненні, як і при порівнянні, ми.. зіставляємо два предмети, але вказуємо не на схожість, а на відмінність" http://sum.in.ua/s/rozriznennja

**Comment by hedrok** [comment]
Тобто diff -> різниця, diffing -> розрізнення?..

**Comment by zmiimz** [comment]
щось таке

**Comment by hedrok** [comment]
+різниця, розрізнення

**Comment by khrystyna-skopyk** [comment]
+різниця, розрізнення
