### ISSUE TITLE
folder, directory (Git directory, working directory)

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#138]
_Опис_: Директорія/тека Git (.git) та робоча директорія/тека сховища.
_Приклад_: This leads us to the three main sections of a Git project: the Git directory, the working directory, and the staging area.

Гадаю, краще буде, якщо в усьому перекладі Git directory та working directory будуть перекладатися однаково, а не як зараз: десь "тека Git", десь "директорія Git".

тека, каталог: 2
тека, тека: 4

**Comment by zmiimz** [comment]
Насправді все просто. Там де був folder,- стала тека, а directory так і залишилась директорією

**Comment by hedrok** [comment]
Тобто ти за "директорія Git" та "робоча директорія"?..
Тут обговорення саме цих двох випадків використання. Особисто мені просто звичніше та коротше "робоча тека" та "тека .git", ніж директорія.
+тека

**Comment by zmiimz** [comment]
Я за те, що тека - це folder, а directory - це директорія. ) В моєму випадку тільки folder я перекладав як тека.

**Comment by hedrok** [comment]
Добре :)

**Comment by khrystyna-skopyk** [comment]
+тека Git, робоча тека

**Comment by hedrok** [comment]
Як цікаво... А чому так?.. Git directory - це просто тека ".git"...

**Comment by KhrystynaK** [comment]
Так, переправила на директорію.

**Comment by khrystyna-skopyk** [comment]
Переправила на директорію, але простіше і легше, мабуть таки тека, я б не робила тут різниці між folder i directory.

**Comment by hedrok** [comment]
Як прикро... Я сподівався, що й там, і там буде "тека" :)

**Comment by hedrok** [comment]
> Переправила на директорію, але простіше і легше, мабуть таки тека, я б не робила тут різниці між folder i directory.

Це вже схоже на тиск з мого боку, проте запитаю: а чому ж "директорія", якщо "тека" простіше та легше?..
Не робити різниці між folder і directory та перекладати обидва терміни як "директорія"?..

**Comment by arysin** [comment]
folder - тека, directory - каталог (хоча різниця розмита, каталог дещо вищого рівня поняття, більше в GUI зустрічається), а от директорія я б не вживав (в укр. це дещо інше)

**Comment by zmiimz** [comment]
Не для всіх. Директор, директорський, директорка, директриса, директорія - всі слова з одного кореня.

**Comment by hedrok** [comment]
Щось я більше не розумію нікого :)
@zmiimz, що ти хотів цим сказати?.. Що "не для всіх"?..

**Comment by zmiimz** [comment]
Проїхали. Я проти каталогу не маю ніяких внутрішніх заперечень
+тека, каталог

**Comment by hedrok** [comment]
@KhrystynaK, я зарахував ваш голос як "директорія, директорія". Якщо я неправильно Вас зрозумів - пишіть.

**Comment by khrystyna-skopyk** [comment]
@hedrok Я за "тека Ґіт, робоча тека"

**Comment by zmiimz** [comment]
Зауваження: directory is a file system cataloging structure which contains references to other computer files, and possibly other directories. 
Тека не говорить про те, що в ній є якась впорядкована структура підтек, а каталог так. В українських лінуксах directory - це каталог.

**Comment by hedrok** [comment]
А можна якісь посилання?.. Що означає "в українських лінуксах"?..

**Comment by zmiimz** [comment]
українська локалізація
http://l10n.kde.org/dictionary/search-translations.php?package=&filename=&teamcode=uk&search=directory&submitted=Search

**Comment by hedrok** [comment]
Як щодо такого компромісу: directory -> каталог, folder -> тека, проте у "working directory" та "Git directory" використовувати "тека". У книзі лише близько десятка використань folder, та 302 directory (з них 140 - це без Git та без working). Мені здається в мовленні набагато більш розповсюджене слово "тека", ніж "каталог" - таким чином ми досягнемо балансу між ними.

**Comment by hedrok** [comment]
(посилання переконливе :) )

**Comment by zmiimz** [comment]
В принципі, компроміс нормальний, потрібно тільки прослідкувати, щоб десь ненароком не втратити  поняття "тека і всі вкладені теки рекурсивно" замінюючи directory-каталог текою.

**Comment by arysin** [comment]
There is a difference between a directory, which is a file system concept, and the graphical user interface metaphor that is used to represent it (a folder). For example, Microsoft Windows uses the concept of special folders to help present the contents of the computer to the user in a fairly consistent way that frees the user from having to deal with absolute directory paths, which can vary between versions of Windows, and between individual installations. Many operating systems also have the concept of "smart folders" that reflect the results of a file system search or other operation. These folders do not represent a directory in the file hierarchy. Many email clients allow the creation of folders to organize email. These folders have no corresponding representation in the filesystem structure.

**Comment by hedrok** [comment]
Я все ж таки виберу "тека, тека", якщо @KhrystynaK не підтримає компроміс чи хтось ще не проголосує за варіант "тека, каталог"... Мені слово "тека" набагато звичніше.

**Comment by mariana-scorp** [comment]
Мені подобається "тека, тека". Коротко, зрозуміло і по-українському :)

**Comment by hedrok** [comment]
Дякую, що знайшли час допомогти. Прикро, що в останній день голосування :)
Добре, наразі в теки чесна перемога )

**Comment by mariana-scorp** [comment]
Мені самій шкода, що не долучилась раніше. Андрій кидав посилання ще два тижні тому, а я якраз грипувати почала тоді.
Ура! "Тека" виграла :)

**Comment by tbudurovych** [comment]
+тек

**Comment by hedrok** [comment]
@tbudurovych, зарахував як "тека, тека". Сподіваюсь, що правильно зрозумів :)
