### ISSUE TITLE
fast-forward, fast-forward merge

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#139]
_Опис_: Злиття без створення коміту зливання, а простим переміщенням вказівника гілки.
_Приклади_:
(fast-forward) Now you can fast-forward your master branch.
(fast-forward merge) At this point, you can go back to the master branch and do a fast-forward merge.

перемота́ння, злиття перемота́нням: 2

**Comment by hedrok** [comment]
~~+перемотка, злиття перемоткою~~

**Comment by khrystyna-skopyk** [comment]
Не дуже подобається "перемотка", змінила б суфікс на "перемота́ння".
+перемота́ння, злиття перемота́нням

**Comment by hedrok** [comment]
Я не проти новотворів, проте є слово "перемотування" http://sum.in.ua/s/peremotuvannja та "перемотка" http://sum.in.ua/s/peremotka, чи варто третє додавати? :)
Але особисто мені теж більше подобається Ваш варіант.
+перемота́ння, злиття перемота́нням

**Comment by khrystyna-skopyk** [comment]
Це не новотвір http://r2u.org.ua/s?w=%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%BE%D1%82%D0%B0%D0%BD%D0%BD%D1%8F&scope=all&dicts=all&highlight=on
Та й до того ж я не дуже довіряю СУМ, бо укладений він був з ідеологічними ідеями.
В будь-якому випадку, я спершу звернула увагу на суфікс в "перемотці", це таке ж слово як "сушка", "зйомка", 
В інших словниках "перемотка" подається тільки як переклад російський http://r2u.org.ua/s?w=%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%BE%D1%82%D0%BA%D0%B0&scope=all&dicts=all&highlight=on

**Comment by hedrok** [comment]
Дійсно, цього разу я на r2u не зазирнув, бо не шукав перекладу з іншої мови... І ґуґл жодної української сторінки з "перемотанням" не знайшов... Це я так виправдовуюсь )
Люблю словники до 33го - завжди можна знайти якесь гарне слово :)
На жаль, мені досі ніхто не назвав жодного словника, якому можна довіряти... Тому й користуюсь СУМом... З тим, що йому не можна довіряти - цілковито погоджуюсь.
