### ISSUE TITLE
fetch, pull

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#140]
_Опис_: Отримання змін з віддаленого сховища. Для pull також спроба злиття/перебазування з поточною гілкою.
_Приклади_:
(fetch) For example, if you want to fetch all the information that Paul has but that you don't yet have in your repository, you can run `git fetch pb`.
(pull) Now, your local branch `sf` will automatically pull from `origin/serverfix`.

здобути зміни, стягнути зміни: 2
стягнути зміни, втягнути зміни: 0

**Comment by hedrok** [comment]
~~+здобути зміни, втягнути зміни (коли неважливо fetch чи pull, використовувати "здобути")''~~

**Comment by khrystyna-skopyk** [comment]
+здобути зміни, стягнути зміни

**Comment by hedrok** [comment]
Ну ось... Все відредагували... :) А мені як раз сподобався варіант:
!стягнути зміни, втягнути зміни

**Comment by hedrok** [comment]
А, побачив, Ви просто пропонуєте pull -> стягнути.

**Comment by arysin** [comment]
pull (як і download) я б сказав «стягнути» (або звантажити)

**Comment by hedrok** [comment]
А fetch?

**Comment by hedrok** [comment]
+здобути зміни, стягнути зміни
