### ISSUE TITLE
fork, to fork, forking

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#143]
_Опис_: Створення власної копії сховища, зазвичай для подальшої роботи та надсилання її до оригінального проекту.
_Приклади_: 
(to fork, fork) The account we just created comes into play when we fork projects and push to our forks a bit later.
(forking) This first example describes contributing via forking on Git hosts that support easy forking.

відсадок: 30; 7 (hedrok) + 5 (zvisno) + 1 (zmiimz) + 9 (arysin) + 7 (mariana-scorp) + 1 (tbydyrovych)
форк: 29; 10 (zvisno) + 1 (zmiimz) + 4 (arysin) + 4 (mariana-scorp) + 10 (tbudurovych)
брунька: 28; 9 (hedrok) + 9 (zmiimz) + 1 (arysin)  + 9 (mariana-scorp)
рукав: 3 (tbudurovych)

брунька, брунькувати, брунькування: 1 zmiimz
відгалуження, створити відгалуження / відгалужити, створення відгалужень: 0 
відсадок, відсаджувати, відсадження: 5 arysin o-pikozh zvisno hedrok mariana-scorp
галузка, розгалужувати, розгалуження: 1 KhrystynaK
щепа, розщеплювати, розщеплення: 0

**Comment by hedrok** [comment]
Тут стільки варіантів: http://slovotvir.org.ua/words/fork
Найнормальніші з моєї суб’єктивної точки зору:
~~+брунька, брунькувати, брунькування~~
!галузка, розгалужувати, розгалуження
!щепа, розщеплювати, розщеплення

Покищо голосую за бруньку, галузка мені не подобається занадто загальним "розгалуження", а "щепа" - дещо деструктивними "розщеплювата" та "розщеплення".

**Comment by zmiimz** [comment]
Брунькування? Це взагалі правильно, але трохи відходить семантично від англійського терміну Але не паратомія, то вже добре :) Мені ще потрібно трохи часу, щоб проголосувати

**Comment by hedrok** [comment]
Оригінально я пропонував на словотворі "розтік" (http://sum.in.ua/s/roztik), проте гадки не маю як від нього утворити to fork та forking :)
Час подумати ще є.

**Comment by khrystyna-skopyk** [comment]
+галузка, розгалужувати, розгалуження

**Comment by arysin** [comment]
Галузка дещо незвично, але схоже галузка, розгалужувати, розгалуження найближче за змістом

**Comment by zmiimz** [comment]
Боюся що 
branch, to branch, branching  - гілка, відгалужувати?, галуження
та
fork, to fork, forking - галузка, розгалужувати, розгалуження
знаходяться надто близько одне від одного, може виникнути непотрібна плутанина

**Comment by hedrok** [comment]
@mariana-scorp, @o-pikozh, @tbudurovych, мені здається аргумент @zmiimz достатньо вагомим, щоб попросити вас обдумати цей issue. Наразі перемагає
галузка, розгалужувати, розгалуження
@zmiimz, може Ви теж за щось проголосуєте? :)

**Comment by mariana-scorp** [comment]
Я згідна з @zmiimz. "Галузка" та "гілка" надто близькі. "Брунька, брунькувати, брунькування" як найадекватніше.

**Comment by o-pikozh** [comment]
А "branch", "to branch", "branching" вже точно як "гілка", "відгалужувати", "галуження"?
Бо "branch" (іменник) -- це однозначно гілка, а от "відгалужувати" і "галуження" (в ролі "to branch" і "branching") мені не подобаються. <sub>По-перше, може заплутувати, адже "гілка" і "галуз(ь)" не є однокорінними (треба запам'ятовувати вдвічі більше термінів замість одного "branch"). По-друге, "відгалужувати" в технічному значенні (не про рослини) означає "відводити вбік дріт, дорогу, канал і т. ін. від їх основного напрямку", а git branch ніякого розгалуження не створює / нічого не відгалужує / не відводить -- новостворена гілка протягнута точнісінько вздовж існуючих комітів -- а власне розгалуження/відгалуження в подальшому створюється комітами в стару і новостворену гілки (причому необов'язково відразу).</sub> Я би використовував "створити гілку" і "створення гілок/гілки" відповідно.

Я за "відгалуження", "створити відгалуження / відгалужити" і "створення відгалужень" для "fork", "to fork" і "forking".

**Comment by zvisno** [comment]
мені подобається брунькування

**Comment by hedrok** [comment]
@zvisno, дякую, що повернулися до нас :)

@o-pikozh, нічого точного ще немає... Проте офіційна дата завершення обговорення словника - 31 січня. А запитів додати до обговорення branching => галуження не було. Я відкрию issue, сподіваюсь хтось ще приєднається до обговорення... #166

**Comment by zmiimz** [comment]
Буде злиття бруньок, синхронізація бруньки, брунькування сховища. :+1: 
+брунька, брунькувати, брунькування

Одне зауваження
Брунька має одну цікаву асоціацію з гілками - branch-ами, а форк - ні англійською, ані українською - немає. , з іншої сторони, форк - це спочатку ніби повний клон сховища ( тому "ботанічно" кращим відповідником був би пагін, росток чи черешок), а брунька - це щось маленьке і на одній гілці. 

ПС Як щодо напрямку "вильця-рогачик" :) ? До речі є ще таке вильце-гільце http://sum.in.ua/s/vyljce

В принципі  якщо зафіксувати переклад branch, to branch, branching - гілка, створити гілку, гілкування 
то 
"відгалуження", "створити відгалуження / відгалужувати" і "створення відгалужень" також вже досить пристойний і розрізнюваний варіант для форку, за який  можу теж проголосувати

**Comment by o-pikozh** [comment]
Post-mortem:

Мені брунька видається досить влучним словом, але трішки смішним. Я маю на увазі: якби ми були творцями GitHub'у, то я б використовував бруньку. Але в випадку коли ми лише перекладачі, я б тяжів до більш тривіальних рішень.

Тим більше, що слово "fork" не є винаходом GitHub'у, це загальновживаний термін. "LibreOffice є брунькою OpenOffice.org" -- ну, я не знаю.

**Comment by hedrok** [comment]
То спробуймо зробити "бруньку" загальновживаним перекладом :)
@zvisno, @zmiimz, @mariana-scorp, Якщо не складно, проголосуйте також за "брунькування" на http://slovotvir.org.ua/words/fork
Дякую.

**Comment by o-pikozh** [comment]
І ще одне.
Брунька завжди маленька (це зародок).
Fork -- це може бути повноцінний окремий проект, що конкурує з оригінальним проектом (за увагу) чи навіть переганяє його (наприклад, якщо оригінальний проект занехаяли).
Тобто, форк починається з "бруньки" (і створення форку як "брункування" -- ок), але існуючий форк -- це зовсім необов'язково брунька.

**Comment by arysin** [comment]
Перепрошую, що відроджую закрите питання, але я погоджуюся, що брунька — це маленьке, менше ніж гілка, а fork - це більше ніж branch:
...So, unlike a branch, a fork is independent from the original repository...
Якщо шукати, щось більше від гілки, то напр. таке http://r2u.org.ua/s?w=%D0%B2%D0%B5%D1%82%D0%B2%D1%8C&scope=all&dicts=all&highlight=on
(одна из главных ветвей, на которые разветвляется дерево) відно́га, ко́нар, га́лузь
(переносно: отрасль) па́рость
(переносно: разветвление чего-л., железнодорожная ветвь, ветвь оврага) ві́тка, рука́в

тому (якщо branch - гілка, гілкування, гілкувати), то для fork можна такі варіанти:
віднога, конар ближче до великого (майже стовбур), але тут є проблема з дієсловами: створювати відногу, конар + незрозуміле слово
парость не дуже бо: пароститися — пускати паростки, проростати — не зовсім те
вітка, віткувати/створювати вітку? але в сучасній мові це майже синонім до гілки

галуза, галузити, галуження — теж в сучасній мові це синонім до гілки

ще є таке:
відсадок — Частина куща, кореневища і т. ін., відокремлена для самостійного проростання (!!!!!)
відсаджувати/відсадження

альтернативно (переклад в лоб):
вилка, (з)вилкувати/створювати вилку, вилкування/створення вилки
тут є семантична проблема, що вилка — це щось роздвоєне, а форк - це лише одна частина вже роздвоєного

або запозичити:
форк, форкувати/створювати форк, форкування/створення форку

**Comment by zvisno** [comment]
можливо переголосуємо  або залишимо форк, дуже неоднозначне у всіх ставлення
не можу не погодитись з останніми двома коментарями

**Comment by arysin** [comment]
Я б сказав відса́док/відса́джувати/відса́дження досить цікавий варіант, але якщо не дійдемо згоди то форк/форкувати (створювати форк)/форкування (створення форку)

**Comment by hedrok** [comment]
~~Лише одне риторичне питання: що заважало це все обговорити тиждень тому?~~ :)
Добре, 20 лютого - новий фінальний строк для обговорення цього питання. Який переклад перемагатиме 20 лютого о 23:59, той і візьмемо, добре?
Я легко підтримаю "відсадок", якщо за нього буде більше, ніж за "бруньку". Можливо навіть, якщо будуть рівні голоси - дійсно більше пасує.
Проте хочу сказати, що аргументи на кшталт "це не зовсім те" на мене не справляють особливого враження - fork, з моєї точки зору, ще менше передає зміст терміну, ніж брунька :)

Насправді, щоб змінити лідера достатньо, щоб @zvisno та @o-pikozh підтримали "відсадок".

**Comment by o-pikozh** [comment]
Я не проти "відсадку".

**Comment by zvisno** [comment]
Мені теж подобається відсадок

**Comment by hedrok** [comment]
@arysin, запропонуйте, будь ласка, цей переклад тут: http://slovotvir.org.ua/words/fork
@o-pikozh, @zvisno, проголосуйте там за нього, будь ласка.
@zmiimz, @mariana-scorp, @KhrystynaK, @tbudurovych, що думаєте про "відсадок" замість "бруньки"?.. Якщо подобається, проголосуйте на словотворі, будь ласка (і тут теж).

+відсадок, відсаджувати, відсадження

**Comment by mariana-scorp** [comment]
Хай буде відсадок. Воно має сенс.

**Comment by zvisno** [comment]
проголосувала

**Comment by zmiimz** [comment]
Відсадок - це вже дуже специфічно і ми занурюємося майже по вуха в маловідому "колгоспну енциклопедію". Брунька, брунькування - дуже хороша асоціація, загальновідома, і погоджуюсь, що це вдаліше за англійський "форк" щонайменше в українській мові, хоча не виключено, що і в англійській теж. Те, що ми передаємо різні смислові значення процесу "форку" (процес зародження, а не наголошуємо на клонуванні) - це нормально, головне, що в нашій мові цей процес все-одно вдалося передати милозвучніше і зрозуміліше. Тому я змінювати голос не буду, і сподіваюсь, що ви також  все-таки прислухаєтесь до звучання термінів і зупинитесь на бруньках.

**Comment by hedrok** [comment]
А я гадав, що ми досягли загального консенсусу та всі задоволені :'(

На захист "відсадка": хоч я це слово ніколи не чув раніше, воно більш влучно передає концепцію, і не обмежується "колгоспною енциклопедією": http://r2u.org.ua/s?w=відсадок&scope=all&dicts=all&highlight=on (Російсько-український академічний словник 1924–33рр. (А. Кримський, С. Єфремов)) тоді цієї енциклопедії ще не було :) Також ґуґл видає все ж таки декілька сторінок з нормальним текстом (http://floristics.info/ua/statti/sadivnitstvo/2486-pukhiroplidnik-posadka-i-doglyad-rozmnozhennya-i-vidi.html тощо)

На захист "бруньки": влучність терміна менша, проте не принципово менша. Слово більш... яскраве, просте. Як і форк в англійській, воно цікаве саме по собі. Гадаю, в нього більше шансів стати розповсюдженим перекладом, ніж у "відсадка" через це. Я швидко змінив свій голос на "відсадок" через те, що гадав, що більшість підтримала "бруньку" лише щоб не було форку, і хвилювався, що занадто впливаю на голосування.

Можливо варто якось інакше голосувати?.. Наприклад від 0 до 10 за обидва варіанти від кожного?.. Який більшу суму отримає, той і візьмемо? Бо мені набридло змінювати думку, обидва варіанти мені подобаються, приблизно в такій пропорції:

брунька: 9 (-1 за те, що не повністю передає зміст терміну)
відсадок: 7
форк: 0

**Comment by zvisno** [comment]
Форк - 10
Відсадок - 5

**Comment by zmiimz** [comment]
брунька - 9
форк - 1
відсадок 1

**Comment by arysin** [comment]
брунька - 1
форк - 4
відсадок - 9

**Comment by tbudurovych** [comment]
я проти "брунька". вважаю що маючи термін "гілка" (branch) і вbодячи щось типу бруньок, наштовхне читача до ієрархічної омани. _wiki: fork ... a copy of source code from one software package and start independent development on it, creating a distinct and separate piece of software._

тому я за форк.

також можливо рукав (типу як в річок), відсадок може бути.

**Comment by mariana-scorp** [comment]
брунька - 9
відсадок - 7
форк - 4

**Comment by hedrok** [comment]
Тарасе, а тобі не складно числа проставити?.. Доки не проставиш, візьму форк 10, рукав 3, відсадок 1. Мені так здалося :)

**Comment by ror6ax** [comment]
Доброго дня. Хочу долучитися до проекту але не знаю звідки почати. Є рекомендації?

**Comment by hedrok** [comment]
Доброго дня. По-перше, можете оцінити тут варіанти перекладу слова "fork" від 0 до 10 (поточні кандидати: відсадок, форк, брунька, рукав)
На питання відповів тут: #168

**Comment by hedrok** [comment]
Перемагає "відсадок, відсаджувати, відсадження."

**Comment by hedrok** [comment]
Прикро, що на словотворі за "відсадок" лише два голоси...
