### ISSUE TITLE
hosting, hosted, to host

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#144]
_Опис_: Сервер, що надає можливість публікувати сховище Git або веб-сайт.
_Приклади_:
We'll go over a few hosted options, if you don't mind hosting your code on someone else's server and don't want to go through the hassle of setting up and maintaining your own server.
A large percentage of all Git repositories are hosted on GitHub, and many open-source projects use it for Git hosting, issue tracking, code review, and other things.

гостинг/хостинг, розташований, розташувати: 1
гостинг (якщо є можливість, уникати), розташований, розташувати: 2
гостинґ, розташований, розташувати: 0
гостиннн, розташований, розташувати: 0

**Comment by hedrok** [comment]
+гостинґ, розташований, розташувати

**Comment by arysin** [comment]
я б не зловживав ґ особливо в кінці слова, зокрема й тому, що в англ. там носовий ŋ: [ˈhəʊstɪŋ]
гостинг/хостинг, розташований, розташувати

**Comment by zmiimz** [comment]
Погоджуюсь на все в розумних межах, що напишете, тільки не хост і хостинг, будь ласка. 
Я б взагалі писав сервер/клієнт, по можливості

**Comment by hedrok** [comment]
Перекладати просто "сервер" - втрачати частину змісту.
Наприклад, я не знаю, як перекласти таке просто з "сервером":

> Next, we'll cover what you'll need to run your own Git repository-hosting server.

Мені найменше подобається гостинг... Найбільше подобався гостинґ, проте ŋ - переконливо...
Тому збирався підтримати хостинг... http://e2u.org.ua/s?w=hosting та https://uk.wikipedia.org/wiki/Хостинг теж за цей варіант.

У тебе є якісь аргументи?.. Можу й гостинг підтримати, проте є https://uk.wikipedia.org/wiki/Гостинг від Ghosting, хоч його й треба було (з моєї точки зору) якось перекласти, або хоча б ґовстинґом зробити (і знову ж таки я ще не знаю, як правильно передати ŋ)...

**Comment by zmiimz** [comment]
там в архівах вікі є посилання
ось уривок http://www.iji.com.ua/hosting.html
Справа в тому, що вікі - не зовсім авторитет, там купу років йде війна між айгевкаючими та айхєвкаючими.
ось ще http://www.stattionline.org.ua/filologiya/52/7173-variantni-nominaci%D1%97-u-suchasnij-ukra%D1%97nskij-movi.html

**Comment by hedrok** [comment]
Авторитетні джерела мені невідомі - інакше я б просто взяв звідти переклад :)
Мені здається, що ŋ найкраще передає "нн". Але "гостинн" напевно занадто сміливо...
Добре, @arysin писав "гостинг/хостинг", @zmiimz "тільки не хостинг", тоді компромісом є "гостинг":
+гостинг, розташований, розташувати

Проте подумайте трошки про "гостинн" :)
!гостинн, розташований, розташувати

**Comment by zmiimz** [comment]
Останнє посилання, яке я дав вище, це
 Алла Таран, Інститут мовознавства ім. О. О. Потебні НАН України (м. Київ), замало авторитету?
Цитата:
"Відповідно до правопису слів іншомовного походження правильним є написання гостинг з-поміж варіантів хостінг – хостинг – гостінг – гостинг."
Можете в неї спитати, чи зараз щось змінилося 
http://ufck.univer.cherkassy.ua/index.php/kafedry/umpl/16-umpl/52-taran

**Comment by hedrok** [comment]
Скажу чесно, коли я відкрив це посилання та побачив купу реклами та купу тексту, я просто закрив її :)
Ось офіційне посилання на цю статтю, яке має .gov.ua та за яким можна завантажити нормальний pdf:  http://www.irbis-nbuv.gov.ua/cgi-bin/irbis_nbuv/cgiirbis_64.exe?I21DBN=LINK&P21DBN=UJRN&Z21ID=&S21REF=10&S21CNR=20&S21STN=1&S21FMT=ASP_meta&C21COM=S&2_S21P03=FILA=&2_S21STR=vdumo_2009_17_15(2)__24 

Єдина аргументація далі в цьому ж абзаці: 

> Згідно з «Українським правописом», у словах іншомовного походження g і h зазвичай передають літерою г. Тому англійське hosting слід писати українською мовою з початковою літерою г і за правилом «дев’ятки» з літерою и.

Втім, "зазвичай" не те саме, що "завжди". Хоч я й ближче до айгевкаючих, проте я ще й айґевкаючий, тому ніколи не міг щиро підтримати це правило :)

Рекомендую просто проголосувати за "гостинг" і буде саме так, як у цій статті.

Якщо є бажання обговорити авторитетність Інституту мовознавства ім. О. О. Потебні НАН України, чинного правопису чи цієї статті - пропоную це зробити на якомусь форумі (наприклад r2u.org.ua) :)

**Comment by zmiimz** [comment]
Перепрошую, в мене просто напевно фільтр реклами, бо я нічого не бачив :) Дискусій, які виходять за практичні потреби, нам дійсно не потрібно, тому я просто уникав цього слова в тексті взагалі, але якщо треба вирішитись, то

+гостинг, розташований, розташувати:

**Comment by hedrok** [comment]
Добре, я додав до нашого варіанту у дужках "якщо є можливість, уникати"
