### ISSUE TITLE
index, staging area, to stage, to unstage, staged

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#145]
_Опис_: Файл, в якому зберігається стан проекту, який буде збережено в наступному коміті. Index та staging area - цілковито одне й те саме, проте в книзі надають перевагу staging area, та пишуть, що index використовувалось раніше.
_Приклади_:
(staging area) The staging area is a file, generally contained in your Git directory, that stores information about what will go into your next commit.
(index) It's sometimes referred to as the ``index'', but it's also common to refer to it as the staging area.
(to stage) You stage the files, adding snapshots of them to your staging area.
(to unstage) For example, to correct the usability problem you encountered with unstaging a file, you can add your own unstage alias to Git.
(staged) If it's modified but has been added to the staging area, it is staged.

індекс, область індексування, покласти в о.і, зніти з о.і, в о.і.: 0
індекс, поміст, покласти на п., зняти з п., на п.: 0
індекс, область додавання, індексувати, деіндексувати, індексований: 0
індекс, область підготовки, підготувати, депідготувати, підготовлений: 0
індекс, область споряджання, спорядити, скасувати споряджання, споряджений: 2

**Comment by arysin** [comment]
Тут непросто, але наприклад такі варіанти:
1) область індексування, покласти в о.і., зняти з о.і.
2) поміст (найблищий прямий переклад до загального значення stage); покласти на п., зняти з п.
3) область споряджання, спорядити/перенести до о.с., скасувати споряджання/зняти з о.с. 
можна ще поміркувати

**Comment by hedrok** [comment]
Довго думав, найбільше мені подобається:
~~+індекс, область споряджання, спорядити, скасувати спорядження, споряджений~~

Ще варіанти:
!індекс, область підготовки, підготувати, депідготувати, підготовлений
!індекс, область додавання, індексувати, деіндексувати, індексований

**Comment by zmiimz** [comment]
подобається, передає те, що потрібно, однак потрібно все-таки вирішитись щодо
СПОРЯ́ДЖЕННЯ чи СПОРЯ́ДЖАННЯ, бо це трохи різні слова

**Comment by hedrok** [comment]
Я мав на увазі споряджання, прикрий одрук вийшов...
~~+індекс, область споряджання, споряджати, скасувати споряджання, споряджений~~
Проте staged -> споряджений, чи є інші пропозиції?..

**Comment by khrystyna-skopyk** [comment]
+індекс, область споряджання, спорядити (!), скасувати споряджання, споряджений
Думаю, "споряджений" хороший варіант

**Comment by hedrok** [comment]
+індекс, область споряджання, спорядити, скасувати споряджання, споряджений

**Comment by hedrok** [comment]
До речі, може краще "зона споряджання"?..

**Comment by zmiimz** [comment]
якщо це один файл (індекс і зона), то може нам тоді не розмножувати сутностей, а зробити з цього один термін? індексний файл чи щось таке?

**Comment by hedrok** [comment]
В оригіналі є index, є staging area - одне й те саме, проте є фрази на кшталт:

> It's sometimes referred to as the ``index'', but it's also common to refer to it as the staging area.

Тому нам потрібен переклад обох термінів. Зараз пропозиція index -> індекс, staging aread -> область споряджання, проте захотілося запропонувати "зона споряджання" замість "області споряджання" - сам не знаю, що краще.

В оригіналі index використовується зрідка, переважно використовується staging area.

**Comment by zmiimz** [comment]
Область ніби приємніше для вух. Можливо варто б давати також " індекс споряджання", щоб було зрозуміліше?

**Comment by hedrok** [comment]
Не знаю, мені достатньо зрозуміло й просто "індекс"... В оригіналі просто index...
Можливо я просто звик...
Приємніше, то приємніше (про область).

**Comment by zmiimz** [comment]
виявляється, боєприпаси в нас теж споряджають, а зворотній процес - це розспоряджання та розспоряджати.  Як альтернатива до "скасувати споряджання", думаю згодиться
!індекс, область споряджання, спорядити/споряджати, скасувати споряджання/розспоряджати, споряджений
