### ISSUE TITLE
issue (GitHub, issue tracking etc)

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#147]
завдання: 3
заява: 1
клопотання: 0
питання: 1
подання: 0
проблема: 0
супліка: 0

_Опис_: Заява про необхідність якихось змін, проблем, пропозицій, тощо.
_Приклад_: We also want to reference an issue in the fork of the repository and an issue in a completely different project.

**Comment by arysin** [comment]
Тут напевне: питання або проблема

**Comment by hedrok** [comment]
Дуже дякую, що долучилися до нашого словника!

Ви маєте на увазі питання/проблема в залежності від контексту, чи це дві окремі пропозиції?..

**Comment by arysin** [comment]
Напевне є сенс затвердити один варіант, це лише пропозиції

**Comment by hedrok** [comment]
~~+завдання~~

**Comment by arysin** [comment]
Завдання це все ж таки task, в таких системах як правило вживаються терміни bug/defect/issue (останній найзагальніший).
Я б сказав «питання» тут найближче (якщо перекладати we have 3 issues to discuss today — маємо три питання на порядку денному).

**Comment by hedrok** [comment]
Пропоную
~~+заява~~
Мені здається за логікою issue найближче до "заяви": це може бути як питання, так і опис проблеми.

**Comment by hedrok** [comment]
А issue tracking -> облік заяв :)

**Comment by zmiimz** [comment]
Ще є подання і клопотання :) 
А tracking може бути і реєстр

реєстр подань
реєстр клопотань
ітд

Хоча я більше схиляюсь до 
проблема
реєстр проблем

Але "створити проблему" звучить дивно :)

**Comment by hedrok** [comment]
Готовий підтримати клопотання/подання, якщо хтось приєднається.
Щодо tracking: я не збирався його додавати до словника, бо дуже зрідка використовується. І мені дуже сподобалось, як Тарас його переклав "облік". Проте якщо треба - створю окремий issue.

**Comment by arysin** [comment]
подання має недолік, що набагато частіше вживається, як дія
клопотання, в цьому плані краще, але воно довше
якщо шукати в цьому напрямку, ще є супліка

**Comment by hedrok** [comment]
А який недолік має "заява"? :) І чи подобається тобі взагалі цей напрямок ("подання", "клопотання" та "супліка" - все ж таки синоніми "заяви")
"Супліка" має велику перевагу: не використовується взагалі (наскільки мені відомо), відповідно стало б чудовим терміном, якби ним всі користувались... Теж готовий підтримати, для мене краще, ніж "подання" та "клопотання".

**Comment by arysin** [comment]
Важко сказати, з одного боку «питання» звичніше, і дещо точніше, воно не викличе «питань» :) але воно багатозначне.

подання/клопотання/супліка — це трішки в сторону мистецтва і художнього пошуку, але якщо його приймуть(!) може бути добрим терміном бо дійсно ніде інде не вживається.
Проблема з цими трьома терімнами, що ми зсуваємося від саме «проблеми/питання», яким є issue, до «заявки/клопотання користувача», тобто трішки втрачається точність.

Скажімо у Андрусишена, Крета є таке (http://e2u.org.ua/s?w=%D1%81%D1%83%D0%BF%D0%BB%D1%96%D0%BA%D0%B0&dicts=all&main_only=on):
суплі́ка (-ки) f Archaic supplication; written petition; request, demand;
  супліка́тор (-ра) m petitioner, supplicant;
  суплікува́ти (-у́ю, -у́єш) I vt to request, beg, ask.
У Кочерги:
зая́ва ... 2. (подання) application

**Comment by zmiimz** [comment]
Так, трохи зсувається суть поняття. Може вдасться відшукати щось схоже на супліку саме до  "проблема-запитання" ?

**Comment by hedrok** [comment]
"Питання" для мене зовсім не те... Якщо хтось підтримає "завдання", я приєднаюсь.
Покищо я налаштований на експеримент із "суплікою" - може хтось прочитає, йому сподобається.
Тобто, якщо ніхто мене не зупинить, я виберу "супліка".
+супліка

**Comment by mariana-scorp** [comment]
Ой, боюсь "супліка" трохи незвична буде. Звісно, можна скористатись нагодою і відновити це слово :) Як щодо "запиту"?

**Comment by hedrok** [comment]
Я думав про "запит", але з ним інша маленька проблема: є request, а також pull request, який ми вирішили перекладати як "запит на злиття". Забагато значень вийде...
"Супліка" буде зовсім незвична, якщо хтось проголосує за завдання або навіть "проблема" я готовий підтримати. Проте "питання" мені здається не зовсім доречним..

**Comment by mariana-scorp** [comment]
Хмм... Так, "питання" надто широке і неоднозначне, а "проблема" має трохи негативного забарвлення. Якщо не виникне плутанини зі словом "завдання", то я за нього. Все-таки ці issues відіграють роль TODO-list'а.

**Comment by hedrok** [comment]
Добре, тоді приєднуюсь до
+завдання.

**Comment by o-pikozh** [comment]
Голосую за "заяву".

**Comment by o-pikozh** [comment]
Просто з точки зору однозначності перекладів.
question -- питання;
task -- завдання;
problem -- проблема;
issue -- заява.

**Comment by tbudurovych** [comment]
+завдання
