### ISSUE TITLE
maintainer

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#149]
доглядач: 0
підтримувач: 0
супровідник: 2
супроводжувач: 1

_Опис_: Людина, яка відповідальна за зливання зовнішніх змін та підтримання проекту в робочому стані.
_Приклад_: That way, the maintainer doesn't have to do any integration work – just a fast-forward or a clean apply.

**Comment by zmiimz** [comment]
супроводжувач, супровідник, доглядач, "підтримувач"

**Comment by arysin** [comment]
супровідник, супроводжувач

**Comment by hedrok** [comment]
Вважатиму, що @zmiimz проголосував за "супроводжувач", а @arysin за супровідник.

**Comment by hedrok** [comment]
+супровідник
