### ISSUE TITLE
merge, to merge

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#150]
_Опис_: Коміт з більш ніж одним батьком -- зʼязвляється через необхідність обʼєднати декілька комітів разом.
_Приклад_: Paul's master branch is now accessible locally as `pb/master` – you can merge it into one of your branches, or you can check out a local branch at that point if you want to inspect it.

злиття, зливати: 3

**Comment by zmiimz** [comment]
- об'єднання - об'єднувати  (поєднання - поєднувати, єднання - єднати)
- злиття - зливати

**Comment by hedrok** [comment]
+злиття, зливати

**Comment by khrystyna-skopyk** [comment]
+злиття, зливати

**Comment by zmiimz** [comment]
+злиття, зливати
