### ISSUE TITLE
patch, patching

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#151]
латка, латати, латання: 3

_Опис_: Файл, що містить зміни до проекту. to patch: застосувати цей файл, тобто відтворити ці зміни.
_Приклади_:
(patch) RCS works by keeping patch sets (that is, the differences between files) in a special format on disk
(patching) You can't stop the patching process with this script.

**Comment by zmiimz** [comment]
латка, латати, латання

**Comment by arysin** [comment]
+1 до латка, латати, латання

**Comment by hedrok** [comment]
+латка, латати, латання
