### ISSUE TITLE
plumbing, porcelain

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#152]
_Опис_: plumbing - внутрішні команди, що їх користувачі зазвичай не використовують напряму. Porcelain - звичайні команди для користувачів.
_Приклади_:
(plumbing) To demonstrate this, we're going to use a low-level command (often referred to as a ``plumbing'' command)
(porcelain) This chapter has covered a number of plumbing commands – commands that are lower level and simpler than the porcelain commands you've learned about in the rest of the book.

залаштункові, сценічні: 0
залаштункові, прилюдні: 1
спідні, парадні: 1.1
кухонні, парадні: 3

**Comment by zmiimz** [comment]
може водогін та порцеляна?

Але якщо була б можливість, я б пошукав якийсь кращий асоціативний ряд, наприклад, склад та вітрина

**Comment by hedrok** [comment]
Тоді "plumbing" команди - водогонні команди?..
"складові команди" може взагалі дуже плутати...
+кухонні, парадні

**Comment by zmiimz** [comment]
ну тоді вже 
світличні, чи вітальні замість парадні

**Comment by tbudurovych** [comment]
+кухонні, парадні

**Comment by arysin** [comment]
+спідні/парадні

**Comment by hedrok** [comment]
@zmiimz, @KhrystynaK, @mariana-scorp, @o-pikozh, цікавить ваша думка.
Гадаю, ми з Тарасом просто вже звикли до "кухонні/парадні". Можливо, "спідні/парадні" вам здаються більш відповідними?
Дякую.

**Comment by o-pikozh** [comment]
Я практично утримуюсь від відповіді. (Мені всі варіанти виглядають занадто оригінальними.) Але моя 1/10 голосу за спідні/парадні.

І ще дурна ідея від мене: залаштункові/прилюдні :).

**Comment by mariana-scorp** [comment]
Ооо! "Залаштункові" - це класно. Мені подобається більше, ніж "спідні" чи "кухонні". Але "прилюдні" не звучить. Треба подумати.

До речі, пасивний стан не притаманний українській мові: "команди, які зазвичай не використовуються напряму користувачами" - це як "підлога, яка помиється студентом". :)

**Comment by hedrok** [comment]
> ...які зазвичай не використовуються напряму користувачами

дякую, виправив

**Comment by mariana-scorp** [comment]
Краса.

**Comment by zvisno** [comment]
мені подобається кухонні, залаштункові - важко вимовляти, але передає добре суть

ще такі слова асоціюються - оригінальні команди, інструментальні, допоміжні

**Comment by hedrok** [comment]
@zvisno, я зарахував голос за "кухонні, парадні". Якщо неправильно зрозумів - пиши )
Не додавав "оригінальні", "інструментальні", "допоміжні" як пропозиції, адже не вистачає перекладу porcelain. Чи всюди ставити "парадні"?..

**Comment by zvisno** [comment]
так, кухонні - парадні

або залаштункові, сценічні
(те що я запропонувала попередньо не потрібно)
