### ISSUE TITLE
pull request

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#153]
запит на втягання: 0
запит на злиття: 3
запит на об’єднання: 0

_Опис_: Пропозиція комусь застосувати зміни з вашого fork.
_Приклад_: When your work has been pushed up to your fork, you need to notify the maintainer.  This is often called a pull request, and you can either generate it via the website – GitHub has its own Pull Request mechanism that we'll go over in <<_github>> – or you can run the `git request-pull` command and e-mail the output to the project maintainer manually.

**Comment by arysin** [comment]
запит на втягання?

**Comment by hedrok** [comment]
Через знак питання просто додав як пропозицію.

!запит на злиття

**Comment by arysin** [comment]
але злиття ближче до merge

**Comment by hedrok** [comment]
Так, але мені здавалося, що значення це особливо не змінює, а звучить краще :)
Сподіваюсь хтось запропонує щось ліпше за обидва ці варіанти...

**Comment by zmiimz** [comment]
Наскільки я розумію термін, то "pull request" не пов'язаний безпосередньо з git pull, ані з git merge командами, точніше обидві використовуються під час опрацювання цього запиту.
Для вибору пропоную "запит на об'єднання"  (якщо є бажання чіткіше відокремити назву-термін від команд),
але вже згаданий "запит на злиття" теж хороший.

**Comment by arysin** [comment]
Логічно, в побуті користуюся "запит на злиття", тож не проти цього варіанту
:)

**Comment by hedrok** [comment]
+запит на злиття

**Comment by zmiimz** [comment]
+запит на злиття

**Comment by khrystyna-skopyk** [comment]
+запит на злиття

Запит на об’єднання може означати А1 А2 А3 + А4 А5 А6 = А1 А2 А3 А4 А5 А6,
а запит на злиття - А1 А2 А3 А4 + А3 А4 А5 А6 = А1 А2 А3 А4 А5 А6.
В другому випадку А3 А4 можуть бути різні і старіший варіант треба змінити на новіший, то й буде злиття (#150).
Це за моєю логікою :)
