### ISSUE TITLE
push

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#154]
_Опис_: Надсилання змін до віддаленого сховища.
_Приклад_: As in any VCS, you can lose or mess up changes you haven't committed yet; but after you commit a snapshot into Git, it is very difficult to lose, especially if you regularly push your database to another repository.

надсилання змін: 2

**Comment by hedrok** [comment]
+надсилання змін

**Comment by khrystyna-skopyk** [comment]
+надсилання змін
