### ISSUE TITLE
reset

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#156]
_Опис_: Зміна вказівника поточної гілки, також можливо індексу та робочої теки. Або скасування змін в індексі для окремого файлу.
_Приклад_: But the Index and Working directory _can_ be partially updated, so reset proceeds with steps 2 and 3.

скидання: 3

**Comment by hedrok** [comment]
+скидання

**Comment by arysin** [comment]
+скидання

**Comment by zmiimz** [comment]
+скидання
