### ISSUE TITLE
revert

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#157]
_Опис_: Отримання змін коміту та застосування їх навпаки, що призводить до скасування змін, проте за допомогою нового коміту.
_Приклад_: The best way around this is to un-revert the original merge, since now you want to bring in the changes that were reverted out, _then_ create a new merge commit.

вивертання, вивернути: 2
(по)вертання, (по)вернути: 1

**Comment by hedrok** [comment]
+вивертання, вивернути

**Comment by arysin** [comment]
+(по)вертання, (по)вернути

**Comment by hedrok** [comment]
Мені подобається "вивернути", бо коли ми робимо revert, ми ніби застосовуємо коміт навпаки (навиворіт). А так виходить, що ми цей коміт "повертаємо"...

**Comment by zmiimz** [comment]
Мені подобається вивернути, але потрібно пошукати, чи нема в книзі слів invert та reverse і узгодити переклад

**Comment by hedrok** [comment]
reverse:

> Notice the reverse order; in reverse chronological order

декілька разів як прикметник "зворотній".

> Reverse the commit:

це саме про git revert, тому переклав "вивертання" (http://git-scm.com/book/uk/v2/Інструменти-Git-Складне-злиття)

> If, on the other hand, you want to see the opposite – all commits in `master` that aren’t in `experiment` – you can reverse the branch names:

тут просто "поміняти місцями" (http://git-scm.com/book/uk/v2/Інструменти-Git-Вибір-ревізій)

> The `git revert` command is essentially a reverse `git cherry-pick`:

переклав

> "Команда `git revert` по суті є `git cherry-pick` навиворіт." (https://github.com/progit/progit2-uk/pull/120/files)

Більше не зустрічається. Крім того не є командою Git, тому можна замінювати різними синонімами.

invert та inverse не зустрічається.

**Comment by zmiimz** [comment]
Добре, а як буде з un-revert? "зворотне вивертання"   (зворотний, без і за нормами правопису)
чи "вивернути назад"?

**Comment by hedrok** [comment]
> The best way around this is to un-revert the original merge

У мене було "вивернути виворіт" :) Але напевно краще виправити на "вивернути вивертання".
un-revert зустрічається лише один раз.

Дякую за зворотнИй, хоча довго не міг второпати про що написано :)

**Comment by zmiimz** [comment]
+вивертання, вивернути
