### ISSUE TITLE
squash, squashed

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#158]
_Опис_: Обʼєднання декількох комітів в один.
_Приклад_: We covered how to do a squashed merge (where Git merges the work but pretends like it's just a new commit without recording the history of the branch you're merging in) at the very end of <<_public_project>>.

зчавлювати, зчавлений: 3

**Comment by tbudurovych** [comment]
зчавлювати?

**Comment by hedrok** [comment]
Чого так невпевнено? :) Я зарахував як +.

**Comment by hedrok** [comment]
+зчавлювати, зчавлений

**Comment by zmiimz** [comment]
+зчавлювати, зчавлений

буде "зчавлене злиття" :)

**Comment by hedrok** [comment]
зчавлювати, зчавлений

**Comment by burlakvo** [comment]
Розумію, що обговорення вже закрите, ще й доволі давно, але зараз ознайомлююсь із розділом 7.6 Переписування історії і там використовується слово "зварювання комітів" (та в інших відмінках). Я переглянув історію комітів і ці терміни вже були перекладені на момент узгодження перекладу.

Власне питання, чи варто чіпати?

Там є й інші невеликі друкарські помилки, тож я все одно вже буду створювати ПР (ЗЗ якось не звично вживати :) ) до правок в цьому файлі

**Comment by zmiimz** [comment]
чіпати завжди варто але запити на злиття не знаю чи будуть завершені, бо Кирило (hedrok) неактивний

**Comment by hedrok** [comment]
@burlakvo @zmiimz дякую, що досі тут :)
Хай як це жалюгідно звучить, від відповіді мене утримувала двофакторна авторизація github )
Але я її нарешті заборов з gpg та https://github.com/WhyNotHugo/totp-cli тож тепер знову маю доступ до github.
Я залив ті PR, в яких було зовсім мало змін і все очевидно. Решту не чіпав.
Докладно розписав усе тут: https://github.com/progit/progit2-uk/issues/205
