### ISSUE TITLE
tag, tagged, to tag, label (GitHub), mark (fast-import)

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#159]
_Опис_:
(tag): Посилання на коміт, що має назву, а також може мати опис, підпис, автора тощо.
(label, GitHub): Те саме, що теґ, тільки в GitHub називається label
(mark, fast-import): Позначка для комітів, директорій, файлів - використовується замість хеш суми під час імпорту із зовнішньої системи до Git.
_Приклади_:
(tag) Like most VCSs, Git has the ability to tag specific points in history as being important.
(tagged) You can see the tag data along with the commit that was tagged by using the `git show` command:
(to tag) Another way to tag commits is with a lightweight tag.
(label, GitHub): What if you need to automate something like adding collaborators or labeling issues?
(mark): You run `print_export` inside each directory, which takes the manifest and mark of the previous snapshot and returns the manifest and mark of this one; that way, you can link them properly.

відмітка, відмічений, відмічати, значок, позначка: 1
мітка, мічений, мітити, значок, позначка: 2
позначка, позначений, позначити, значок, мітка: 0
теґ, позначений теґом, позначити теґом, значок, позначка: 0

**Comment by zmiimz** [comment]
ярлик, бирка, наклейка, наліпка , мітка, позначка

Я більш схиляюсь до "мітка -- мічений -- мітити"
Але потрібно узгодити переклад для label та mark, -- як позначка та марка, наприклад, якщо вони є чи з'являться десь в книзі.

**Comment by hedrok** [comment]
label у всій книзі зустрічається виключно в контексті GitHub, там ми дійсно перекладали "мітка".
Багато mark як дієслова: "mark file as" тощо. Це перекладали як "позначити", "question mark" не конфліктує, markers - позначки. Є також в 09-git-and-other-scms/sections/import-custom.asc "mark", яке я переклав "позначка". Це, фактично, ідентифікатор комітів та інших речей в тому контексті.

**Comment by hedrok** [comment]
!мітка, мічений, мітити, ярлик, позначка
!позначка, позначений, позначити, якрлик, мітка
!теґ, позначений теґом, позначити теґом, ярлик, позначка

**Comment by hedrok** [comment]
Переборов свою тягу до ґ, та вирішив, що позначка мені подобається більше, тому:
~~+позначка, позначений, позначити, якрлик, мітка~~

**Comment by zmiimz** [comment]
+відмітка, відмічений, відмічати, значок, позначка

ярлика не хочу

**Comment by hedrok** [comment]
Не хочеш - не треба :)
+позначка, позначений, позначити, значок, мітка

**Comment by hedrok** [comment]
Якщо ніхто більше не проголосує, я виберу тут свій варіант. Для мене звичніше "позначка".

**Comment by mariana-scorp** [comment]
Мені "мітка" подобається :)

**Comment by hedrok** [comment]
Напишіть, будь ласка, свій варіант повністю: як перекладати tag, tagged, to tag, label (GitHub), mark (fast-import).
Бо в моєму варіанті є мітка для mark... Чи Ви про варіант "мітка, мічений, мітити, значок, позначка" (ярлик замінив на значок, бо zmiimz проти слова "ярлик")?..

**Comment by mariana-scorp** [comment]
Так, перепрошую. Я, власне, мала на увазі "мітку" для слова tag. Тож я за "мітка, мічений, мітити" для "tag, tagged, to tag". Коротоко і зрозуміло, як на мене. "Значок, позначка" буде гарно для "label (GitHub), mark (fast-import)".

**Comment by hedrok** [comment]
@zmiimz, підтримаєш цей варіант?.. Він нібито близький до твого...
Тоді мені не доведеться вибирати між "мітка/відмітка/позначка" :)

**Comment by hedrok** [comment]
+мітка, мічений, мітити, значок, позначка
