### ISSUE TITLE
to track (file), tracked (file), untracked (file), to track (branch)

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#160]
_Приклади_:
(to track file) If you want to start version-controlling existing files (as opposed to an empty directory), you should probably begin tracking those files and do an initial commit.
(tracked files) At this point, you have a Git repository with tracked files and an initial commit.
(untracked files) Untracked files are everything else – any files in your working directory that were not in your last snapshot and are not in your staging area.
(to track branch) If you have a branch set up to track a remote branch (...), you can use the `git pull` command to automatically fetch and then merge a remote branch into your current branch.

доглядати (файл), під доглядом (файл), не під доглядом (файл), слідкувати (за гілкою): 0
контролювати (файл), контрольований (файл), неконтрольований (файл), слідкувати (за гілкою): 0
стежити (за файлом), відстежуваний (файл), невідстежуваний (файл), стежити (за гілкою): 3
стежити (за файлом), стежений (файл), нестежений (файл), стежити (за гілкою): 0

**Comment by hedrok** [comment]
Вилучив "tracked (branch)", бо "Managing remote repositories includes knowing how to add remote repositories, remove remotes that are no longer valid, manage various remote branches and define them as being tracked or not, and more" -- єдине речення, в якому tracked стосується гілок, і це не прикметник, а просто третя форма дієслова.

!доглядати (файл), під доглядом (файл), не під доглядом (файл), слідкувати (за гілкою)
!контролювати (файл), контрольований (файл), неконтрольований (файл), слідкувати (за гілкою)

**Comment by hedrok** [comment]
Хоча слова "стежений" словники не фіксують, разом з ним виходить все логічно:
~~+стежити (за файлом), стежений (файл), нестежений (файл), стежити (за гілкою)~~

**Comment by khrystyna-skopyk** [comment]
+стежити (за файлом), простежений або відстежений (краще навіть відстежений) (файл), нестежений (файл), стежити (за гілкою)

Простежений і відстежений передають доконану дію, але по суті в прикладі "At this point, you have a Git repository with tracked files and an initial commit." можна й так перекласти "з відстеженими файлами та початковим комітом."
Ми стежимо за файлом, споряджаємо його ( #145) і він стає відстежений.

**Comment by hedrok** [comment]
Як я розумію, tracked - це все ж таки прикментник, що означає, що Git постійно стежить за файлом, а не відстежив його один раз і все.

**Comment by zmiimz** [comment]
![p_302](https://cloud.githubusercontent.com/assets/1889372/12576607/3a83cd72-c415-11e5-824f-f43499a0823e.png)
стійкий дієприкметник в українській для цього був би ВІДСТЕЖУВАНИЙ. Але це якраз для tracked
untracked -- невідстежуваний

**Comment by hedrok** [comment]
+стежити (за файлом), відстежуваний (файл), невідстежуваний (файл), стежити (за гілкою)

**Comment by zmiimz** [comment]
+стежити (за файлом), відстежуваний (файл), невідстежуваний (файл), стежити (за гілкою)

**Comment by khrystyna-skopyk** [comment]
так, +за відстежуваний

**Comment by hedrok** [comment]
стежити (за файлом), відстежуваний (файл), невідстежуваний (файл), стежити (за гілкою)
