### ISSUE TITLE
executable

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#161]
_Опис_: Чи можна виконати файл.
_Приклад_: We'll save our helper as `git-credential-read-only`, put it somewhere in our `PATH` and mark it executable.

виконавчий: 0
викона́нний: 3
виконуваний: 0

**Comment by hedrok** [comment]
+викона́нний

**Comment by zmiimz** [comment]
executable: викона́нний [файл]. Я знаю, що це слово є в e2u, але там трохи "швидка настя" в перекладі, бо і виконуваний і виконавчий і командний і виконАнний. Мені здається, що виконавчий чи виконуваний більш відомі. Я б взагалі перекладав просто "програма", по можливості.

**Comment by hedrok** [comment]
Коли є можливість, програмою й перекладаємо. Але саме коли в оригіналі "mark as executable" чи "any properly named executable script", де треба підкреслити, що він спрацює, якщо executable, такої можливості немає.

**Comment by tbudurovych** [comment]
+викона́нний

**Comment by khrystyna-skopyk** [comment]
+викона́нний

**Comment by hedrok** [comment]
викона́нний
