### ISSUE TITLE
З Новим Роком та Різдвом

### ISSUE THREAD

**Issue by tbudurovych** [progit/progit2-uk#165]
Вітаю команду, що долучається чи співчуває перекладу.
Бажаю багато часу та натхнення для нових знань та здобутків!

**Comment by hedrok** [comment]
Вітаю всіх з Новим Роком!
Всім дякую за співпрацю :)

**Comment by webknjaz** [comment]
:wine_glass:

**Comment by zmiimz** [comment]
thnx, навзаєм! )
