### ISSUE TITLE
branching

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#166]
_Опис_: Система створення гілок
_Приклад_: 
It's incredibly fast, it's very efficient with large projects, and it has an incredible branching system for non-linear development

галуження: 0
гілкування: 3

**Comment by hedrok** [comment]
Ми весь час перекладали "галуження", і в мені не спадало на думку щось інше. Проте @o-pikozh написав про те, що "галуження" від "галузь", і я знайшов таке цікаве слово:
http://sum.in.ua/s/ghilkuvannja
!галуження
+гілкування

**Comment by hedrok** [comment]
@tbudurovych, як ти ставишся до такого?..

**Comment by o-pikozh** [comment]
Мені гілкування подобається більше.

**Comment by zmiimz** [comment]
То що
branch, to branch, branching - гілка, створити гілку, гілкування?
+гілкування

**Comment by hedrok** [comment]
branch - гілка все ж таки не підлягає сумніву :)
to branch - я просто не пам’ятаю, щоб таке було, гадаю трапляється дуже зрідка, і в цьому випадку дійсно варто писати "створити гілку". Пошукаю ще...
