### ISSUE TITLE
Сказати розробникам, що переклад готовий, а не translation started

### ISSUE THREAD

**Issue by gruz** [progit/progit2-uk#179]
Коли написано, що переклад лише розпочато почато, то насторожує. Значить не все зробелно, неузгоджені терміни. Ліпше вже англійською читати. А тут все готово насправді.

В наших братів-кацапів написано, що книжка перекладена. Але в них переклад версії 1. Тобто гірший, ніж цей. Треба виправити цю несправедливість. З рештою несправедливостей від братів-кацапів розберемось силою зброї і дещо пізніше.

<a href="http://static.xscreenshot.com/2016/07/09/08/screen_03c04f940120dd43ba1c4cb4afb2bab2" rel="group[xscreenshot]"  class="jcepopup" data-mediabox-height="600" data-mediabox-group="xscreenshot" data-mediabox-width="800"><img width="300" src="http://static.xscreenshot.com/2016/07/09/08/screen_03c04f940120dd43ba1c4cb4afb2bab2"></a>

P.S. Тут на гіті в братів-кацапів є друге видання. Дивно, чого на сайті книги на перше посилається. Так їм і треба.

**Comment by hedrok** [comment]
Мені дуже хочеться спочатку оновити терміни.
Ми все переклали, а потім переузгодили терміни, коли вже все було готово.
Я вважатиму переклад завершеним, коли буде виконано https://github.com/progit/progit2-uk/issues/170. Наразі можливо дійсно краще англійську читати, оскільки в різних розділах навіть commit може бути перекладено по різному.
Коли це буде зроблено, просто створимо запит на злиття до https://github.com/git/git-scm.com
Якщо візьмешся виконати #170 буду безмежно вдячний. Схожи ані я, ані Тарас (@tbudurovych) не можемо зараз знайти час для цього.

P.S. У справі перекладів принципово не дивлюся на переклади на інші мови, які знаю, щоб не заважало. Перекладаю як можу з оригіналу. Тому що там у дальніх родичів росіян не впливає на мою думку :)

**Comment by gruz** [comment]
Та я певно не долучусь більше, ніж зробив. У мене "громадського навантаження" і так вище даху. 
Я, власне, коли побачив, що все ж комміти по-різному називаються в тексті, кинув читати. 
Я не можу знайти, де ці узгоджені терміни і де ті. які використовувались? Без знання що раніше було, важко виправляти.

Якщо не для мене, то для прийдешніх поколінь треба викласти у вікі.

**Comment by hedrok** [comment]
Так, доволі прикро, що нам трошки не вистачило енергії на завершення...
Дякую, що завітали й трохи повиправляли )
Для прийдешніх поколінь розписав там все.
Що кинули читати зовсім прикро :( Треба якось знайти час і все завершити...

**Comment by gruz** [comment]
Де розписав? Я не можу знайти де дивитись на узгоджені і старі терміни. Ткніть пальцем, б.л. :-)

**Comment by hedrok** [comment]
У потрібному issue: https://github.com/progit/progit2-uk/issues/170
wiki ми взагалі тут не використовували, мені здається issue тут достатньо... Проте якщо тобі це якось допоможе, можу ввімкнути wiki й там розписати. :)

**Comment by hedrok** [comment]
Конкретно на старі не вийде, бо фактично три людини спочатку паралельно писали, та й не факт, що притримувались одних термінів самі (я, наприклад, спочатку експериментував з усілякими "фіксаціями", "пхати" тощо, а потім мене переконали використовувати дещо нормальнішу термінологію). Тому варто дивитися оригінал, як я там і написав.

**Comment by gruz** [comment]
Я би терміни оздоблював би, наприклад, жирним.  

Або ще  ліпше чимось на подобу тега ABBR в HTML. Щоби в терміні було зашито буржуїнський відповідник. Тоді і змінити можна просто по пошуку. Зараз що шукати? Я бачив слово знімок к в тексті. А в обговорення #170 його нема. 
А якби був аналог ABBR, то при наведенні ще і спливало би буржуїнське слово.

Якщо вони будуть переїжджати з того атласіана чи що там у них, то вони і синтаксис можуть поміняти? Якщо так, то взагалі паритись нема сенсу.
