### ISSUE TITLE
Чогось HTMLentities вилізли

### ISSUE THREAD

**Issue by gruz** [progit/progit2-uk#180]
Ось скріншот
<a href="http://static.xscreenshot.com/2016/07/09/09/screen_2792d67375b1c483e1c734d80bcccfe1" rel="group[xscreenshot]"  class="jcepopup" data-mediabox-height="600" data-mediabox-group="xscreenshot" data-mediabox-width="800"><img width="300" src="http://static.xscreenshot.com/2016/07/09/09/screen_2792d67375b1c483e1c734d80bcccfe1"></a>

Певно при зборці вилазить. Бо в git що англійської, що української - однаково. 

В інших місцях так само псує знаки **<** і **>**

**Comment by hedrok** [comment]
У сховищі оригіналу вже є з цього приводу issue: https://github.com/progit/progit2/issues/371
Відповідно, цей закриваю.
Взагалі, якщо проблема є в оригіналі, то в перекладі не виправляємо (хоча я подеколи порушую це правило, але лише якщо вже створив PR до оригіналу, наприклад https://github.com/progit/progit2/pull/589)
