### ISSUE TITLE
Неможливо скачати український варіант

### ISSUE THREAD

**Issue by tolikvasylyk** [progit/progit2-uk#184]
Доброго дня!
На сайті https://git-scm.com/book/en/v2 книга доступна для скачування лише на англійській мові. Український варіант книги скачати не можна. Чи можете ви розмістити згенеровану книжку в себе на репозиторії, щоб вона була доступна для скачування?

**Comment by hedrok** [comment]
Доброго дня!
Обов'язково подивлюся протягом тижня.
Переклад, на жаль, не вичитаний, буду дуже вдячний, якщо писатимете зауваження під час читання.

**Comment by hedrok** [comment]
Виправлено, можете завантажувати: https://git-scm.com/book/uk/v2
