### ISSUE TITLE
 bleeding-edge branches

### ISSUE THREAD

**Issue by stayathome** [progit/progit2-uk#193]
Слововсполучення  "bleeding-edge branches" в book/03-git-branching/sections/workflows.asc (4 абзац) перекладено як "кровоточащі" :-)
Доречніше вжити щось типу "найновіші" чи "найсвіжіші" або "гілки на передньому краю вашого коду" :-)

**Comment by hedrok** [comment]
"кровоточащі" це було сильно, дякую.
Довго думав, на що б виправити.
Тут https://ukrainian.stackexchange.com/questions/1149/%d0%af%d0%ba-%d0%bf%d0%b5%d1%80%d0%b5%d0%ba%d0%bb%d0%b0%d1%81%d1%82%d0%b8-bleeding-edge/1150#1150 є обговорення, але пропоновані варіанти "кривавий край" та "скривавлений край" не набагато ліпші за те, що зараз.
Поставив "дослідницькі":

```
Насправді, ми маємо справу з вказівниками, що рухаються вздовж лінії комітів, які ви додаєте.
Стабільні гілки нижче по лінії ваших комітів, а "`дослідницькі`" гілки -- ті що містять нові зміни, випереджують їх.
```

Альтернативні пропозиції приймаються.
