### ISSUE TITLE
Please fix the book in order to enable publishing

### ISSUE THREAD

**Issue by jnavila** [progit/progit2-uk#196]
Right now, the book cannot be compiled because of some mistakes. Please refer to build log : https://github.com/progit/progit2-uk/runs/3150442436 in order to find where the errors are.

Until the book compiles without errors, the new versions of the book cannot be compiled to epub, mobi, pdf and html.

**Comment by hedrok** [comment]
Hi @jnavila! Fixed at last thanks to @burlakvo.
