### ISSUE TITLE
setting-up-server: Source-code differs from orig

### ISSUE THREAD

**Issue by tbudurovych** [progit/progit2-uk#2]
I suggest to not change source code. in this case jessica -> olga etc

https://github.com/progit/progit2-uk/commit/94f1168f4467f5e4a0d953e6a9c45dd45513405d#diff-6d7b7a99df70ad8681092d3f48427767R48

**Comment by hedrok** [comment]
Повиправляв усюди, де я таке робив: #3
Також додав загальні правила, де описав, що перекладати імена не треба.
Чекаю на рев’ю :)

**Comment by tbudurovych** [comment]
merged
