### ISSUE TITLE
Написання з великої літери при перекладі

### ISSUE THREAD

**Issue by VBoden** [progit/progit2-uk#6]
Пропоную при перекладі не писати окремі слова з великої літери аналогічно як це пишеться в англійській версії. Наприклад, у заголовках "Гілки у Кількох Словах", "Процеси Роботи з Гілками", "Варіанти Стороннього Хостингу" та навіть у "Основи Галуження та Зливання" з великої літери писати лише перше слово. Це все загальні назви і відповідно до правил правопису повинні писатись з малої літери. В англійській мові свої правила, у нашій - свої. По-моєму, це виглядає якось кострубато.
Що ви на це скажете?

**Comment by hedrok** [comment]
Я підтримую. Я просто не знав, що в англійській мові розповсюджене явище писати
кожне слово в заголовках з великої літери, тому зберіг як в оригіналі.  Якщо
@greatehop або @tbudurovych теж підтримають, зроблю зміни та PR.

**Comment by tbudurovych** [comment]
слушно
