### ISSUE TITLE
contributors.asc

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#64]
Перекласти файл contributors.asc

**Comment by unreadablename** [comment]
@hedrok я б хотів перекласти цей файл, список контриб'юторів поповнити перекладачами?

**Comment by hedrok** [comment]
Я продивився декілька інших перекладів - наразі жоден з них не наважився додавати туди перекладачів...
У будь-якому разі, це легше буде зробити, коли переклад буде завершено, ніж оновлювати щоразу й status.json, і contributors.asc :)
@tbudurovych, як вважаєш?..

**Comment by unreadablename** [comment]
@hedrok @tbudurovych перекладачів можна окремим списком в цьому файлі, як варіант
