### ISSUE TITLE
Для новачків - переклад розділів

### ISSUE THREAD

**Issue by VBoden** [progit/progit2-uk#7]
Пропоную тут писати які розділи заброньовано для перекладу і який наступний розділ вільний, щоб нові люди могли бачити, що вони можуть взяти.
Це питання залишити відкритим і оновлювати відповідно до статусу.

**Comment by hedrok** [comment]
Мені здається, ця інформація має бути тут: https://github.com/hedrok/progit2-uk/blob/master/TRANSLATION_NOTES.asc
Увечері додам восьмий розділ на тебе.
Ну і про всяк випадок дублюю тут:

03-git-branching: tbudurovych
05-distributed-git: greatehop
07-git-tools: hedrok
08-customizing-git: VBoden
09-git-and-other-scms: наступний вільний

**Comment by tbudurovych** [comment]
привіт,

я якраз закінчив розділ і подумав ...

можна ще зробити дошку в trello і там візуально трекати що треба переклади і що а якому стані. кожен айтем це один файл. і брати не по розділу а по файлу. Таким чином більш живий переклад буде.

я можу спробувати налаштувати для прикладу.

що скажете ?

**Comment by hedrok** [comment]
Мені теж здається, що розділ - забагато. Тим паче невдовзі вони закінчаться :)
Але я пропоную просто відкривати PR щойно починаєш переклад: перекласти тільки перший рядок файла, зробити коміт "Початок перекладу path-to-file" та відкривати PR.
Прямо в TRANSLATION_NOTES це все прописати, і що обов’язково на кожен файл по окремому PR.
А перед початком перекладу кожен має переглянути, які файли зайняті. Таким чином ми обмежимось функціоналом GitHub і не будемо примушувати перекладачів використовувати щось ще.
Але можемо спробувати й trello - я просто ніколи ним не користувався.

**Comment by VBoden** [comment]
Я також думаю, що краще обмежитись функціоналом GitHub.

**Comment by tbudurovych** [comment]
Тоді так і зробимо, обмежимось github-ом

**Comment by tbudurovych** [comment]
попросив додати мітку для PR - https://github.com/progit/progit2/issues/417

**Comment by hedrok** [comment]
Додав мітки

**Comment by hedrok** [comment]
Додав PR https://github.com/progit/progit2-uk/pull/16
