### ISSUE TITLE
hook

### ISSUE THREAD

**Issue by tbudurovych** [progit/progit2-uk#82]
Чи гук? Чи просто гак?

тобто 
хук, гук, гак.

тут їх багато - https://github.com/progit/progit2-uk/pull/81

Мені **гак** ок.

/cc @hedrok @zvisno

**Comment by tbudurovych** [comment]
http://slovotvir.org.ua/words/khuk for inspiration

**Comment by hedrok** [comment]
Натхнення - це чудово, проте гадаю "стусану" всі дуже здивуються :)
Я спочатку перекладав "гак", якщо пам’ятаєш. Проте ви та вікі мене переконали: https://uk.wikipedia.org/wiki/Перехоплення_(інформатика)
Повернімо "гак", я тільки за.

**Comment by zvisno** [comment]
я за гак або хук. гук не дуже зрозуміло і не зручно вимовляти.

**Comment by hedrok** [comment]
Добре, хай буде "гак". Issue не закриваю, бо треба повиправляти всюди в тексті.

**Comment by zvisno** [comment]
домовились

**Comment by hedrok** [comment]
Відкриваю, бо @webknjaz не згоден з "гак". Чекаємо на пропозиції від нього.
