### ISSUE TITLE
Закінчення не перекладених термінів (наприклад Git)

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#83]
Розглянемо речення "great feature of Git"
Як її перекладати:
1. Чудова властивість Git
2. Чудова властивість Git'у
3. Чудова властивість Git-у
?
Бо в нас вже є всі три варіанти, і на додаток варіанти з а/у в родовому відмінку.
Ми використовували 1, проте я не проти 2, тоді я за закінчення "у" для Git.
@tbudurovych ?..

**Comment by zvisno** [comment]
я за 1 і за 2, тому @tbudurovych вирішуй :)

**Comment by VBoden** [comment]
мені більше подобається варіант 1

**Comment by hedrok** [comment]
Забув додати всіх :) @tbudurovych @greatehop @zvisno @mzelenyuk @VBoden

**Comment by tbudurovych** [comment]
Я за 1)

Через те що до нього найменше питань.

Am Donnerstag, 22. Oktober 2015 schrieb Kyrylo Yatsenko :

> Забув додати всіх :) @tbudurovych https://github.com/tbudurovych
> @greatehop https://github.com/greatehop @zvisno
> https://github.com/zvisno @mzelenyuk https://github.com/mzelenyuk
> @VBoden https://github.com/VBoden
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/progit/progit2-uk/issues/83#issuecomment-150347813.

## 

## 

Best Regards, Taras Budurovych

**Comment by mzeleniuk** [comment]
Однозначно перший або другий варіант. Але голосую за перший.

**Comment by webknjaz** [comment]
Голосую за перший варіант, бо інакше будуть ще суперечки на тему гіт`А` чи гіт`У`, наприклад.

**Comment by tbudurovych** [comment]
значить вердикт
1. Чудова властивість Git
