### ISSUE TITLE
default

### ISSUE THREAD

**Issue by hedrok** [progit/progit2-uk#84]
У нас всі перекладають default по своєму.
Особисто я перекладаю "без додаткових опцій" або "типово".
Тарас, здається, пише "за замовчуванням" (цей варіант мені особливо не подобається :) )
Юлія пропонує незрозумілий мені, проте цікавий варіант "поза вибором"
Тут ще багато дивних варіантів: http://slovotvir.org.ua/words/default
Прошу допомоги у всіх, адже мені, насправді, жоден з варіантів не дуже подобається: @tbudurovych @greatehop @zvisno @mzelenyuk @VBoden

**Comment by VBoden** [comment]
не пам’ятаю, як я перекладав, але давайте, можливо, будемо використовувати "типово, типове значення"? я думаю, можна орієнтуватись на http://e2u.org.ua/s?w=default&dicts=3&highlight=on

**Comment by mzeleniuk** [comment]
Мені найбільше подобається "типово".

**Comment by tbudurovych** [comment]
> типово

я не проти

Єдине, що default це - ["a value automatically assigned"](https://en.wikipedia.org/wiki/Default_%28computer_science%29)

В той час як _типове_ - це _найбільш поширене_, моя думка. Наприклад

_Типовим значeнням для поля 'Gender' буде 'M' чи 'F'. А by default (тобто нічого не роблячи) буде порожня стрічка._

Тому якщо я десь прочитаю що _типовим значенням буде порожня стрічка_, я це розумітиму як те, що в досить велик. к-сті значкння порожнє.

не знаю чи вдало виклав думку.

**Comment by hedrok** [comment]
Ти чудово виклав думку, саме через це мені й не подобається цей варіант. Якби існував варіант, що мені до вподоби, я б написав тобі коментар до "за замовчуванням". Я довго думав, та запропонував на словотворі "нестачне, за нестачею".
Доки ця моя геніальна пропозиція не запанує в тенетах, готовий на використання варіанту "типово" :)
