### ISSUE TITLE
Gitter chat channel

### ISSUE THREAD

**Issue by webknjaz** [progit/progit2-uk#90]
Hi guys,

I suggest using https://gitter.im to discuss translation problems in real time. It's a slack-like app for github-repo binded chats.

@hedrok could you create channel at https://gitter.im/progit/progit2-uk? or tag ones who can.

TIA.

/cc: @tbudurovych @greatehop @ben

**Comment by hedrok** [comment]
@ben, sorry to disturb you - we'll first decide whether we need this, then if we decide that we need it, we'll try to make it ourselves, and if we can't do it - then we'll ask you. Please ignore this thread for now.

Привіт :)
По-перше, будь ласка, не відволікай ben'а - він один з авторів оригіналу, навіть якщо виключно він може створити чат в gitter.im, гадаю, його варто кликати лише коли ми вирішимо, що чат нам потрібен.

Особисто я ніколи ним не користувався, ти міг би надати декілька переваг над простими Issue в github  (зі slack я теж не працював).?..

Ми намагались обмежитись функціоналом github, вже були пропозиції підключити зовнішній Issue Tracker, проте позначок та issue github нам достатньо. Ми просто створюємо issue для обговорення слова, та обговорюємо його там...

**Comment by webknjaz** [comment]
Там можна в реальному часі спілкуватися. Ось тобі й перевага при необхідності всі плюшки типу маркдауна, підвантаження зовнішніх ресурсів, на які посилаються в повідомленнях прямо у чат. Інтеграції, якщо необхідно. Можна тегати людей, є десктопні/мобільні клієнти. На пошту можуть падати "згадки" тебе, якщо хтось тегнув чи останні повідомлення (якщо ввімкнуто).

В Україні туди переїхали купа чатиків, які до того "жили" у скайпі. Приблизно рік тому було вичерпано ліміт місць (300) в публічному чаті FrontendUA й був створений https://gitter.im/dev-ua/frontend-ua (просто залогінитися через гітхаб)

Ось тут можеш побачити цілий список їх: https://github.com/dev-ua

Це не панацея і не заміна гітхабу (issues лишаються, хоча й можна налаштувати, щоб їх оновлення падали в чат теж), просто додатковий зручний інструмент взаємодії в команді.
Наприклад, я можу спитати "Як перекласти verb в такому-то контексті?" й усі одразу побачать (якщо онлайн). За сприятливих умов, я можу одразу кілька думок/рішення одержати.

Звісно, це не буде примусовим використанням інструменту, та все ж зручним засобом для тих, кому потрібно.

**Comment by hedrok** [comment]
Я, виявляється, не дописав повідомлення тут :)
Я створив чат https://gitter.im/hedrok/progit2-uk-test, не вдалося туди додати @VBoden, @mzelenyuk та @zvisno. Якщо бажаєте, приєднуйтесь.

**Comment by webknjaz** [comment]
@hedrok вони мабуть ніколи не заходили в гіттер і не мають там облікового запису. до речі, не обов’язково було приписувати `-test`
крім того, я би додав бейджик з лінком туди в репозиторій? не проти?

**Comment by hedrok** [comment]
Та хто ж знав, що всі одразу почнуть там спілкуватися? :) Я гадав, це буде test... Крім того не знав, чи будуть проблеми через те, що існує сховище hedrok/progit2-uk.
Я не проти. Якщо можеш - додавай, якщо потрібно, щоб я щось зробив - напиши що )
Я перевіряв - progit/progit2-uk дійсно можуть зробити лише власники progit.
Є якісь мінуси від того, що наш чат hedrok/progit2-uk-test?..

**Comment by webknjaz** [comment]
Мінус лиш в неочевидності. Можна просто перестворити новий без тест чи попросити власників (поки там мало повідомлень). А як ні - я можу вже додати кнопку в рідмі, це не проблема зовсім.

а щодо

> чи будуть проблеми через те, що існує сховище hedrok/progit2-uk

в початковій версії гіттера можна було створювати чат лише до існуючого репозиторія, це тепер вже можна й з кастомною адресою :)

**Comment by tbudurovych** [comment]
Чат добра ідея. Ми мали gitter ще на початку перекладу з
https://github.com/greatehop. Не пішло. Сподіваюся зараз піде коли більше
народу.

**Comment by hedrok** [comment]
Здається мені, і цього разу ця добра ідея "не пішла". Не бачу необхідності турбувати власників progit для створення "офіційного" чату.
